Peninjauan awal dilakukan untuk melakukan penanganan setiap noise yang mungkin terdapat pada data (seperti missing value, kesalahan penamaan, ketidaksesuaian tipe data, serta hal-hal lainnya)

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

### Import Sheets Data

In [2]:
table_sell_in = pd.read_excel("DATA DUMMY SALES.xlsx", sheet_name="Sell In")
table_sell_out = pd.read_excel("DATA DUMMY SALES.xlsx", sheet_name="Sell Out")
table_CA = pd.read_excel("DATA DUMMY SALES.xlsx", sheet_name="CA")
table_survey = pd.read_excel("DATA DUMMY SALES.xlsx", sheet_name="Survey")

#### Melihat sekilas table Sell In

In [3]:
table_sell_in.head(2)

,tahun,bulan,tanggal,regional,opco_area,province_code,province_desc,district_code,district_desc,brand,material_code,material_desc,delivery_type,baseunit_of_measure,shipto,shipto_desc,soldto,soldto_desc,plant,plant_name,area_name,segment,segment_material,quantity,revenue,incoterm
0,2026,1,1,AREA 5,ST,1035,SULAWESI TENGGARA,103502,KOTA KENDARI,Atlas,MAT003,Atlas Semen Tecton Khusus,ZLC,BAG,WH-1035-01,Gudang Sulawesi Tenggara 01,SD-1035-03,PT Distributor Sulawesi Tenggara 03,PL-005,Pabrik Pangkep,AREA 79 KENDARI,MB,Retail Bag,47.04,58768765,Pickup
1,2026,1,1,AREA 4,SG,1026,BALI,102601,KABUPATEN BADUNG,Vanguard,MAT003,Vanguard Semen Tecton Khusus,ZLC,BAG,WH-1026-02,Gudang Bali 02,SD-1026-01,PT Distributor Bali 01,PL-004,Pabrik Tuban,AREA 57 DENPASAR,MB,Retail Bag,36.08,40532235,Pickup

In [4]:
table_sell_in.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15439 entries, 0 to 15438
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   tahun                15439 non-null  int64
 1   bulan                15439 non-null  int64
 2   tanggal              15439 non-null  int64
 3   regional             15439 non-null  object
 4   opco_area            15439 non-null  object
 5   province_code        15439 non-null  int64
 6   province_desc        15439 non-null  object
 7   district_code        15439 non-null  int64
 8   district_desc        15439 non-null  object
 9   brand                15439 non-null  object
 10  material_code        15439 non-null  object
 11  material_desc        15439 non-null  object
 12  delivery_type        15439 non-null  object
 13  baseunit_of_measure  15439 non-null  object
 14  shipto               15439 non-null  object
 15  shipto_desc          15439 non-null  object
 16  soldto               15439 non-null  object
 17  soldto_desc          15439 non-null  object
 18  plant                15439 non-null  object
 19  plant_name           15439 non-null  object
 20  area_name            15439 non-null  object
 21  segment              15439 non-null  object
 22  segment_material     15439 non-null  object
 23  quantity             15439 non-null  float64
 24  revenue              15439 non-null  int64
 25  incoterm             15439 non-null  object
dtypes: float64(1), int64(6), object(19)
memory usage: 3.1+ MB

In [5]:
table_sell_in.describe()

,tahun,bulan,tanggal,province_code,district_code,quantity,revenue
count,15439.0,15439.000000,15439.000000,15439.000000,15439.000000,15439.000000,1.543900e+04
mean,2026.0,6.522443,15.831466,1025.952847,102596.976747,80.102058,9.020399e+07
std,0.0,3.450950,8.746881,9.754851,975.438661,40.615994,4.669620e+07
min,2026.0,1.000000,1.000000,1010.000000,101001.000000,10.020000,9.837172e+06
25%,2026.0,4.000000,8.000000,1017.000000,101702.000000,45.035000,4.989086e+07
50%,2026.0,7.000000,16.000000,1025.000000,102503.000000,79.830000,8.909659e+07
75%,2026.0,10.000000,23.000000,1034.000000,103403.000000,115.710000,1.292943e+08
max,2026.0,12.000000,31.000000,1043.000000,104302.000000,150.000000,1.942579e+08

In [6]:
print(f"Jumlah data duplikat pada tabel ini: {table_sell_in.duplicated().sum()}")
print(f"Jumlah missing value pada tabel ini: {table_sell_in.isna().sum()}")

Jumlah data duplikat pada tabel ini: 0
Jumlah missing value pada tabel ini: tahun                  0
bulan                  0
tanggal                0
regional               0
opco_area              0
province_code          0
province_desc          0
district_code          0
district_desc          0
brand                  0
material_code          0
material_desc          0
delivery_type          0
baseunit_of_measure    0
shipto                 0
shipto_desc            0
soldto                 0
soldto_desc            0
plant                  0
plant_name             0
area_name              0
segment                0
segment_material       0
quantity               0
revenue                0
incoterm               0
dtype: int64

#### Melihat sekilas table Sell Out

In [7]:
table_sell_out.head(2)

,tanggal_trx,provinsi,kode_toko,nama_toko,kode_gudang,nama_gudang,kode_distributor,kabupaten_gudang,sum(tonase)
0,2026-01-01,ACEH,TK-WH-1010-02-1,TB Jaya 1,WH-1010-02,Gudang Aceh 02,SD-1010-03,KOTA BANDA ACEH,51.23
1,2026-01-01,ACEH,TK-WH-1010-02-5,TB Sejahtera 5,WH-1010-02,Gudang Aceh 02,SD-1010-03,KOTA BANDA ACEH,29.46

In [8]:
table_sell_out.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49167 entries, 0 to 49166
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   tanggal_trx       49167 non-null  datetime64[ns]
 1   provinsi          49167 non-null  object
 2   kode_toko         49167 non-null  object
 3   nama_toko         49167 non-null  object
 4   kode_gudang       49167 non-null  object
 5   nama_gudang       49167 non-null  object
 6   kode_distributor  49167 non-null  object
 7   kabupaten_gudang  49167 non-null  object
 8   sum(tonase)       49167 non-null  float64
dtypes: datetime64[ns](1), float64(1), object(7)
memory usage: 3.4+ MB

In [9]:
table_sell_out.describe()

                         tanggal_trx   sum(tonase)
count                          49167  49167.000000
mean   2026-07-02 17:50:54.805052160     22.634848
min              2026-01-01 00:00:00      0.000000
25%              2026-04-01 00:00:00      6.170000
50%              2026-07-03 00:00:00     14.660000
75%              2026-10-03 00:00:00     29.470000
max              2026-12-31 00:00:00    346.280000
std                              NaN     25.068451

In [10]:
print(f"Jumlah data duplikat pada tabel ini: {table_sell_out.duplicated().sum()}")
print(f"Jumlah missing value pada tabel ini: {table_sell_out.isna().sum()}")

Jumlah data duplikat pada tabel ini: 0
Jumlah missing value pada tabel ini: tanggal_trx         0
provinsi            0
kode_toko           0
nama_toko           0
kode_gudang         0
nama_gudang         0
kode_distributor    0
kabupaten_gudang    0
sum(tonase)         0
dtype: int64

#### Melihat sekilas tabel CA

In [11]:
table_CA.head(2)

,brands_Fondalit,source,nama_gudang,tonase,tonase LT,tonase_total,area,provinsi,kabupaten,kecamatan,kode_toko,nama_toko,kode LT,nama_LT,nama_produk,area_name,kode_diAtlasributor,toko_type,quantity,tanggal_trx,brand,uom,kluAtlaser,Atlasatus_brand,nama_diAtlasributor,brand_short,jenis_zak,opco_area,tanggal_refresh,kode_gudang
0,TerraBlock,CA,Gudang Aceh 02,87.12,0.0,87.12,AREA 1,ACEH,KOTA BANDA ACEH,Kecamatan ACEH 2,TK-KOT-958,Toko Maju KOT,-,-,TerraBlock Semen PCC Premium,AREA 01 BANDA ACEH,SD-1010-03,Retail,87.12,2026-01-01,TerraBlock,TON,Bronze,Main Brand,PT DiAtlasributor Aceh 03,AND,40,Fonda,2026-06-10,WH-1010-02
1,Fonda,CA,Gudang Jambi 02,95.84,0.0,95.84,AREA 1,JAMBI,KOTA JAMBI,Kecamatan JAMBI 2,TK-KOT-445,Toko Sentosa KOT,-,-,Fonda Semen Portland Tipe I,AREA 18 JAMBI,SD-1015-02,Retail,95.84,2026-01-01,Fonda,TON,Platinum,Main Brand,PT DiAtlasributor Jambi 02,Fonda,50,Fonda,2026-06-10,WH-1015-02

In [12]:
table_CA.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15383 entries, 0 to 15382
Data columns (total 30 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   brands_Fondalit      15383 non-null  object
 1   source               15383 non-null  object
 2   nama_gudang          15383 non-null  object
 3   tonase               15383 non-null  float64
 4   tonase LT            15383 non-null  float64
 5   tonase_total         15383 non-null  float64
 6   area                 15383 non-null  object
 7   provinsi             15383 non-null  object
 8   kabupaten            15383 non-null  object
 9   kecamatan            15383 non-null  object
 10  kode_toko            15383 non-null  object
 11  nama_toko            15383 non-null  object
 12  kode LT              15383 non-null  object
 13  nama_LT              15383 non-null  object
 14  nama_produk          15383 non-null  object
 15  area_name            15383 non-null  object
 16  kode_diAtlasributor  15383 non-null  object
 17  toko_type            15383 non-null  object
 18  quantity             15383 non-null  float64
 19  tanggal_trx          15383 non-null  datetime64[ns]
 20  brand                15383 non-null  object
 21  uom                  15383 non-null  object
 22  kluAtlaser           15383 non-null  object
 23  Atlasatus_brand      15383 non-null  object
 24  nama_diAtlasributor  15383 non-null  object
 25  brand_short          15383 non-null  object
 26  jenis_zak            15383 non-null  int64
 27  opco_area            15383 non-null  object
 28  tanggal_refresh      15383 non-null  object
 29  kode_gudang          15383 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(1), object(24)
memory usage: 3.5+ MB

In [13]:
table_CA.describe()

,tonase,tonase LT,tonase_total,quantity,tanggal_trx,jenis_zak
count,15383.000000,15383.000000,15383.000000,15383.000000,15383,15383.000000
mean,66.398518,8.422355,74.820873,74.820873,2026-07-02 00:00:22.466358784,44.991874
min,5.350000,0.000000,8.140000,8.140000,2026-01-01 00:00:00,40.000000
25%,35.845000,0.000000,41.740000,41.740000,2026-04-01 00:00:00,40.000000
50%,64.060000,0.000000,74.450000,74.450000,2026-07-02 00:00:00,40.000000
75%,94.620000,10.885000,107.310000,107.310000,2026-10-01 00:00:00,50.000000
max,240.140000,121.660000,259.780000,259.780000,2026-12-31 00:00:00,50.000000
std,35.860811,15.666032,38.540381,38.540381,NaN,5.000156

In [14]:
print(f"Jumlah data duplikat pada tabel ini: {table_CA.duplicated().sum()}")
print(f"Jumlah missing value pada tabel ini: {table_CA.isna().sum()}")

Jumlah data duplikat pada tabel ini: 0
Jumlah missing value pada tabel ini: brands_Fondalit        0
source                 0
nama_gudang            0
tonase                 0
tonase LT              0
tonase_total           0
area                   0
provinsi               0
kabupaten              0
kecamatan              0
kode_toko              0
nama_toko              0
kode LT                0
nama_LT                0
nama_produk            0
area_name              0
kode_diAtlasributor    0
toko_type              0
quantity               0
tanggal_trx            0
brand                  0
uom                    0
kluAtlaser             0
Atlasatus_brand        0
nama_diAtlasributor    0
brand_short            0
jenis_zak              0
opco_area              0
tanggal_refresh        0
kode_gudang            0
dtype: int64

#### Melihat sekilas table Survey

In [15]:
table_survey.head(2)

,survey_date,no_survey,visit_id,visit_date,tahun,bulan,hari,checkin_time,checkout_time,checkin_latitude,checkin_longitude,cuAtlasomer_code,cuAtlasomer_name,cluAtlaser_name,provinsi_id,provinsi,area_id,area_name,kabupaten_id,kabupaten,sap_code,salesman,salesman_id,diAtlasributor_code,diAtlasributor_name,salesman.1,id_salesman,id_supervisor,supervisor,product_code,product_name,Atlasock,volume_sales,coAtlas_price,order_date,volume_order,sale_price,kapasitas_jual,kapasitas_gudang,kemasan,brand,brand_group
0,2026-01-01,SRV-20260101-9741,VAtlas-20260101-760,2026-01-01,2026,1,1,15:18:00,15:50:00,-4.745121,113.307903,CUAtlas-102002-1,Toko Survey 102002 1,Platinum,1020,BANTEN,Omnicore,AREA 33 BANTEN,102002,KOTA SERANG,SAP-CUAtlas-102002-1,Salesman N39,SLS-039,SD-1020-01,PT DiAtlasributor Banten 01,Salesman N39,SLS-039,FondaV-009,Supervisor Q9,PRD-939,Semen Fonda Atlasandar,313,73,46625,2025-12-25,95,65039,567,710,40 Kg,Fonda,SIG
1,2026-01-01,SRV-20260101-9615,VAtlas-20260101-895,2026-01-01,2026,1,1,11:07:00,11:46:00,-5.936172,127.528086,CUAtlas-104002-0,Toko Survey 104002 0,Platinum,1040,MALUKU UTARA,Atlas,AREA 91 MALUKU UTARA,104002,KOTA TERNATE,SAP-CUAtlas-104002-0,Salesman M38,SLS-038,SD-1040-02,PT DiAtlasributor Maluku Utara 02,Salesman M38,SLS-038,FondaV-009,Supervisor Q9,PRD-154,Semen Kinetiq Atlasandar,163,42,50110,2025-12-28,73,61993,289,1333,40 Kg,Kinetiq,SIG

In [16]:
table_survey_same = table_survey[table_survey['salesman_id'] == table_survey['id_salesman']]
table_survey_same.shape

(8350, 42)

In [17]:
table_survey_same_date = table_survey[table_survey['survey_date'] == table_survey['visit_date']]
table_survey_same_date.shape

(8350, 42)

In [18]:
table_survey.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8350 entries, 0 to 8349
Data columns (total 42 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   survey_date          8350 non-null   datetime64[ns]
 1   no_survey            8350 non-null   object
 2   visit_id             8350 non-null   object
 3   visit_date           8350 non-null   datetime64[ns]
 4   tahun                8350 non-null   int64
 5   bulan                8350 non-null   int64
 6   hari                 8350 non-null   int64
 7   checkin_time         8350 non-null   object
 8   checkout_time        8350 non-null   object
 9   checkin_latitude     8350 non-null   float64
 10  checkin_longitude    8350 non-null   float64
 11  cuAtlasomer_code     8350 non-null   object
 12  cuAtlasomer_name     8350 non-null   object
 13  cluAtlaser_name      8350 non-null   object
 14  provinsi_id          8350 non-null   int64
 15  provinsi             8350 non-null   object
 16  area_id              8350 non-null   object
 17  area_name            8350 non-null   object
 18  kabupaten_id         8350 non-null   int64
 19  kabupaten            8350 non-null   object
 20  sap_code             8350 non-null   object
 21  salesman             8350 non-null   object
 22  salesman_id          8350 non-null   object
 23  diAtlasributor_code  8350 non-null   object
 24  diAtlasributor_name  8350 non-null   object
 25  salesman.1           8350 non-null   object
 26  id_salesman          8350 non-null   object
 27  id_supervisor        8350 non-null   object
 28  supervisor           8350 non-null   object
 29  product_code         8350 non-null   object
 30  product_name         8350 non-null   object
 31  Atlasock             8350 non-null   int64
 32  volume_sales         8350 non-null   int64
 33  coAtlas_price        8350 non-null   int64
 34  order_date           8350 non-null   datetime64[ns]
 35  volume_order         8350 non-null   int64
 36  sale_price           8350 non-null   int64
 37  kapasitas_jual       8350 non-null   int64
 38  kapasitas_gudang     8350 non-null   int64
 39  kemasan              8350 non-null   object
 40  brand                8350 non-null   object
 41  brand_group          8350 non-null   object
dtypes: datetime64[ns](3), float64(2), int64(12), object(25)
memory usage: 2.7+ MB

In [19]:
table_survey.describe()

,survey_date,visit_date,tahun,bulan,hari,checkin_latitude,checkin_longitude,provinsi_id,kabupaten_id,Atlasock,volume_sales,coAtlas_price,order_date,volume_order,sale_price,kapasitas_jual,kapasitas_gudang
count,8350,8350,8350.0,8350.000000,8350.000000,8350.000000,8350.000000,8350.000000,8350.000000,8350.000000,8350.000000,8350.000000,8350,8350.000000,8350.000000,8350.000000,8350.000000
mean,2026-07-01 12:12:25.005988096,2026-07-01 12:12:25.005988096,2026.0,6.510898,15.690180,-2.473860,117.403573,1025.569581,102558.707305,255.696766,52.515569,49979.541796,2026-06-27 12:34:29.461078016,103.815449,63078.852096,545.361796,1102.946826
min,2026-01-01 00:00:00,2026-01-01 00:00:00,2026.0,1.000000,1.000000,-9.999453,95.002594,1010.000000,101001.000000,10.000000,5.000000,45000.000000,2025-12-25 00:00:00,10.000000,56000.000000,100.000000,200.000000
25%,2026-04-01 00:00:00,2026-04-01 00:00:00,2026.0,4.000000,8.000000,-6.236515,106.290056,1018.000000,101801.000000,135.000000,29.000000,47485.500000,2026-03-28 00:00:00,57.000000,59599.250000,323.000000,660.000000
50%,2026-07-02 00:00:00,2026-07-02 00:00:00,2026.0,7.000000,16.000000,-2.481847,117.341833,1025.000000,102501.000000,256.000000,52.000000,49967.500000,2026-06-28 00:00:00,102.000000,63088.000000,542.000000,1098.000000
75%,2026-09-30 00:00:00,2026-09-30 00:00:00,2026.0,9.000000,23.000000,1.285348,128.408234,1033.000000,103302.000000,376.000000,76.000000,52466.500000,2026-09-26 00:00:00,151.000000,66571.500000,768.000000,1544.750000
max,2026-12-31 00:00:00,2026-12-31 00:00:00,2026.0,12.000000,31.000000,4.996108,139.993143,1043.000000,104302.000000,500.000000,100.000000,55000.000000,2026-12-30 00:00:00,200.000000,70000.000000,1000.000000,2000.000000
std,NaN,NaN,0.0,3.441806,8.772497,4.332340,12.855760,9.293649,929.325866,141.210079,27.530437,2892.369486,NaN,55.001735,4036.304233,259.470169,516.558396

In [20]:
print(f"Jumlah data duplikat pada tabel ini: {table_survey.duplicated().sum()}")
print(f"Jumlah missing value pada tabel ini: {table_survey.isna().sum()}")

Jumlah data duplikat pada tabel ini: 0
Jumlah missing value pada tabel ini: survey_date            0
no_survey              0
visit_id               0
visit_date             0
tahun                  0
bulan                  0
hari                   0
checkin_time           0
checkout_time          0
checkin_latitude       0
checkin_longitude      0
cuAtlasomer_code       0
cuAtlasomer_name       0
cluAtlaser_name        0
provinsi_id            0
provinsi               0
area_id                0
area_name              0
kabupaten_id           0
kabupaten              0
sap_code               0
salesman               0
salesman_id            0
diAtlasributor_code    0
diAtlasributor_name    0
salesman.1             0
id_salesman            0
id_supervisor          0
supervisor             0
product_code           0
product_name           0
Atlasock               0
volume_sales           0
coAtlas_price          0
order_date             0
volume_order           0
sale_price             0
kapasitas_jual         0
kapasitas_gudang       0
kemasan                0
brand                  0
brand_group            0
dtype: int64

#### Hasil temuan awal dari setiap table

1. Table Sell In
- Kolom tahun, bulan, tanggal dipisahkan (akan digabung dan diubah formatnya menjadi bentuk datetime)
- Terdapat id penting (provinsi, distrik, kode material, kode pengiriman, kode penjualan, plan)
- Jika melihat kolom numeriknya, tidak ada nilai yang diluar konteks kolom (menjadi anomali)
- Tidak ditemukan adanya data duplikat pada baris data dan missing value pada setiap kolom

2. Table Sell Out
- Terdapat id penting (kode toko, kode gudang, dan kode distributor)
- Jika melihat kolom numeriknya, terdapat sum(tonase) yang nilainya 0 (akan dicari tahu lebih lanjut)
- Tidak ditemukan adanya data duplikat pada baris data dan missing value pada setiap kolom

3. Table CA
- Terdapat nama kolom yang disusupi frasa 'Atlas' yang harusnya diganti menjadi 'st'
- Jika dalam baris data tidak ada nilai tonase_LT, kode_LT dan nama_LT akan ikut kosong
- Tidak ditemukan adanya data duplikat pada baris data
- Kolom tanggal_refresh perlu diubah formatnya menjadi datetime
- Jika melihat kolom numeriknya, tidak ada nilai yang diluar konteks kolom (menjadi anomali)

4. Table Survey
- Terdapat nama kolom yang disusupi frasa 'Atlas' yang harusnya diganti menjadi 'st'
- Terdapat 2 kolom yang akan dihapus karena isinya identik terkait dengan id salesman dan nama salesman
- Terdapat 4 kolom (tanggal, bulan, tanggal, survey_date) yang dihapus karena sudah terangkum pada kolom visit_date
- Jika melihat kolom numeriknya, tidak ada nilai yang diluar konteks kolom (menjadi anomali)

### Penanganan Awal Setiap Temuan pada Data

#### Mengganti alias 'Atlas' menjadi 'st'

In [21]:
table_CA = table_CA.rename(columns={
    'kode_diAtlasributor' : 'kode_distributor',
    'kluAtlaser' : 'kluster',
    'Atlasatus_brand' : 'status_brand',
    'nama_diAtlasributor' : 'nama_distributor'
})

In [22]:
table_CA.columns

Index(['brands_Fondalit', 'source', 'nama_gudang', 'tonase', 'tonase LT',
       'tonase_total', 'area', 'provinsi', 'kabupaten', 'kecamatan',
       'kode_toko', 'nama_toko', 'kode LT', 'nama_LT', 'nama_produk',
       'area_name', 'kode_distributor', 'toko_type', 'quantity', 'tanggal_trx',
       'brand', 'uom', 'kluster', 'status_brand', 'nama_distributor',
       'brand_short', 'jenis_zak', 'opco_area', 'tanggal_refresh',
       'kode_gudang'],
      dtype='object')

In [23]:
table_survey = table_survey.rename(columns={
    'cuAtlasomer_code': 'customer_code',
    'cuAtlasomer_name': 'customer_name',
    'cluAtlaser_name': 'cluster_name',
    'diAtlasributor_code': 'distributor_code',
    'diAtlasributor_name': 'distributor_name',
    'Atlasock': 'stock',
    'coAtlas_price': 'cost_price'
})

In [24]:
table_survey.columns

Index(['survey_date', 'no_survey', 'visit_id', 'visit_date', 'tahun', 'bulan',
       'hari', 'checkin_time', 'checkout_time', 'checkin_latitude',
       'checkin_longitude', 'customer_code', 'customer_name', 'cluster_name',
       'provinsi_id', 'provinsi', 'area_id', 'area_name', 'kabupaten_id',
       'kabupaten', 'sap_code', 'salesman', 'salesman_id', 'distributor_code',
       'distributor_name', 'salesman.1', 'id_salesman', 'id_supervisor',
       'supervisor', 'product_code', 'product_name', 'stock', 'volume_sales',
       'cost_price', 'order_date', 'volume_order', 'sale_price',
       'kapasitas_jual', 'kapasitas_gudang', 'kemasan', 'brand',
       'brand_group'],
      dtype='object')

#### Mengubah tipe data kolom

In [25]:
table_sell_in['date'] = pd.to_datetime(table_sell_in[['tahun', 'bulan', 'tanggal']].rename
(columns={'tahun':'year', 'bulan':'month', 'tanggal':'day'}))

In [26]:
table_sell_in = table_sell_in.drop(columns=['tahun', 'bulan', 'tanggal'])

In [27]:
table_CA['tanggal_refresh'] = pd.to_datetime(table_CA['tanggal_refresh'])

In [28]:
table_CA.dtypes

brands_Fondalit             object
source                      object
nama_gudang                 object
tonase                     float64
tonase LT                  float64
tonase_total               float64
area                        object
provinsi                    object
kabupaten                   object
kecamatan                   object
kode_toko                   object
nama_toko                   object
kode LT                     object
nama_LT                     object
nama_produk                 object
area_name                   object
kode_distributor            object
toko_type                   object
quantity                   float64
tanggal_trx         datetime64[ns]
brand                       object
uom                         object
kluster                     object
status_brand                object
nama_distributor            object
brand_short                 object
jenis_zak                    int64
opco_area                   object
tanggal_refresh     datetime64[ns]
kode_gudang                 object
dtype: object

#### Menghapus kolom duplikat pada tabel survey

In [29]:
table_survey = table_survey.drop(columns=['salesman.1', 'id_salesman', 'tahun', 'bulan', 'hari', 'survey_date'])

### Pengecekan Nilai Kategorikal Setiap Tabel

In [30]:
pd.set_option('display.max_rows', None)

def check_categorical_value(name_df):
    list_categorical = name_df.select_dtypes(include=['object']).columns.tolist()

    for col in list_categorical:
        print(f'Kolom {col} memiliki {name_df[col].nunique()} kategori unik.')
        print(name_df[col].value_counts())
        print('-----------------------------------\n\n')

#### Table Sell In

In [31]:
check_categorical_value(table_sell_in)

Kolom regional memiliki 5 kategori unik.
regional
AREA 5    6384
AREA 1    3088
AREA 3    2595
AREA 4    2109
AREA 2    1263
Name: count, dtype: int64
-----------------------------------


Kolom opco_area memiliki 5 kategori unik.
opco_area
ST      6384
SP      3088
SBI     2595
SG      2109
SMBR    1263
Name: count, dtype: int64
-----------------------------------


Kolom province_desc memiliki 34 kategori unik.
province_desc
JAMBI                        865
JAWA TENGAH                  852
RIAU                         480
SULAWESI SELATAN             467
SUMATERA UTARA               462
KEPULAUAN BANGKA BELITUNG    460
NUSA TENGGARA TIMUR          448
KEPULAUAN RIAU               443
KALIMANTAN SELATAN           441
BENGKULU                     440
PAPUA                        440
KALIMANTAN TENGAH            439
MALUKU                       432
DKI JAKARTA                  432
ACEH                         432
KALIMANTAN UTARA             432
NUSA TENGGARA BARAT          430
SUMATERA SELATAN             427
DI YOGYAKARTA                427
KALIMANTAN BARAT             425
BANTEN                       421
PAPUA BARAT                  421
SULAWESI TENGAH              419
BALI                         419
SULAWESI BARAT               419
SULAWESI TENGGARA            417
JAWA BARAT                   415
JAWA TIMUR                   414
SUMATERA BARAT               412
KALIMANTAN TIMUR             410
MALUKU UTARA                 404
GORONTALO                    403
SULAWESI UTARA               401
LAMPUNG                      390
Name: count, dtype: int64
-----------------------------------


Kolom district_desc memiliki 81 kategori unik.
district_desc
KOTA JAMBI                      443
KABUPATEN MUARO JAMBI           422
KOTA SURAKARTA                  298
KOTA SEMARANG                   284
KABUPATEN BANYUMAS              270
KABUPATEN KAMPAR                257
KABUPATEN MAROS                 246
KABUPATEN REJANG LEBONG         241
KABUPATEN DELI SERDANG          239
KABUPATEN BANGKA                237
KABUPATEN BADUNG                233
KABUPATEN LOMBOK BARAT          229
KABUPATEN MALUKU TENGAH         229
KABUPATEN KUPANG                224
KOTA KUPANG                     224
KOTA JAYAPURA                   224
KOTA PEKANBARU                  223
KOTA PANGKAL PINANG             223
KOTA MEDAN                      223
KOTA BANDA ACEH                 222
KABUPATEN BULUNGAN              222
KOTA MAKASSAR                   221
KOTA PALEMBANG                  221
KOTA SORONG                     219
KABUPATEN KUBU RAYA             218
KABUPATEN JAYAPURA              216
KABUPATEN KONAWE                210
KABUPATEN POSO                  210
KOTA TARAKAN                    210
KABUPATEN ACEH BESAR            210
KOTA PALU                       209
KABUPATEN HALMAHERA UTARA       208
KOTA KENDARI                    207
KOTA PONTIANAK                  207
KOTA MANADO                     206
KABUPATEN MUARA ENIM            206
KOTA GORONTALO                  204
KOTA AMBON                      203
KABUPATEN MANOKWARI             202
KOTA MATARAM                    201
KABUPATEN GORONTALO             199
KOTA BENGKULU                   199
KOTA TERNATE                    196
KABUPATEN MINAHASA              195
KOTA DENPASAR                   186
KOTA JAKARTA BARAT              157
KOTA BATAM                      156
KABUPATEN BANTUL                156
KABUPATEN POLEWALI MANDAR       153
KOTA YOGYAKARTA                 151
KOTA SERANG                     151
KABUPATEN BANJAR                151
KABUPATEN KOTAWARINGIN TIMUR    148
KABUPATEN KAPUAS                147
KOTA BANDUNG                    146
KOTA BANJAR BARU                145
KOTA TANJUNG PINANG             145
KOTA BANJARMASIN                145
KOTA BUKIT TINGGI               144
KOTA PALANGKA RAYA              144
KOTA JAKARTA SELATAN            143
KOTA BALIKPAPAN                 142
KABUPATEN BINTAN                142
KOTA BOGOR                      141
KOTA CILEGON                    140
KOTA PADANG                     139
KOTA MALANG                     139
KOTA SAMARINDA                  139
KABUPATEN SIDOARJO              138
KABUPATEN LAMPUNG SELATAN       138
KOTA SURABAYA                   137
KABUPATEN MAJENE                136
KOTA BANDAR LAMPUNG             134
KOTA JAKARTA TIMUR              132
KABUPATEN TANGERANG             130
KABUPATEN MAMUJU                130
KABUPATEN KUTAI KARTANEGARA     129
KABUPATEN PADANG PARIAMAN       129
KABUPATEN BOGOR                 128
KABUPATEN SLEMAN                120
KOTA METRO                      118
Name: count, dtype: int64
-----------------------------------


Kolom brand memiliki 9 kategori unik.
brand
Atlas         6384
TerraBlock    1568
Fonda         1520
Monolith      1263
Primebase     1067
Vanguard      1042
Tecton         882
Omnicore       861
Kinetiq        852
Name: count, dtype: int64
-----------------------------------


Kolom material_code memiliki 4 kategori unik.
material_code
MAT002    3948
MAT004    3889
MAT003    3827
MAT001    3775
Name: count, dtype: int64
-----------------------------------


Kolom material_desc memiliki 36 kategori unik.
material_desc
Atlas Semen PCC Premium               1640
Atlas Semen Portland Komposit         1604
Atlas Semen Tecton Khusus             1598
Atlas Semen Portland Tipe I           1542
TerraBlock Semen Portland Komposit     421
TerraBlock Semen Tecton Khusus         401
Fonda Semen Portland Tipe I            391
Fonda Semen Portland Komposit          390
TerraBlock Semen PCC Premium           384
Fonda Semen PCC Premium                375
Fonda Semen Tecton Khusus              364
TerraBlock Semen Portland Tipe I       362
Monolith Semen PCC Premium             333
Monolith Semen Tecton Khusus           328
Monolith Semen Portland Komposit       301
Monolith Semen Portland Tipe I         301
Primebase Semen PCC Premium            284
Vanguard Semen Portland Tipe I         271
Primebase Semen Portland Tipe I        268
Vanguard Semen PCC Premium             263
Primebase Semen Portland Komposit      260
Vanguard Semen Portland Komposit       256
Primebase Semen Tecton Khusus          255
Vanguard Semen Tecton Khusus           252
Kinetiq Semen PCC Premium              248
Omnicore Semen Portland Tipe I         233
Tecton Semen Tecton Khusus             231
Tecton Semen Portland Komposit         229
Kinetiq Semen Portland Komposit        225
Tecton Semen Portland Tipe I           220
Omnicore Semen PCC Premium             219
Omnicore Semen Tecton Khusus           206
Omnicore Semen Portland Komposit       203
Tecton Semen PCC Premium               202
Kinetiq Semen Tecton Khusus            192
Kinetiq Semen Portland Tipe I          187
Name: count, dtype: int64
-----------------------------------


Kolom delivery_type memiliki 4 kategori unik.
delivery_type
ZLC     3922
ZSLF    3860
ZLF     3834
ZLFP    3823
Name: count, dtype: int64
-----------------------------------


Kolom baseunit_of_measure memiliki 2 kategori unik.
baseunit_of_measure
BAG    7865
ZAK    7574
Name: count, dtype: int64
-----------------------------------


Kolom shipto memiliki 68 kategori unik.
shipto
WH-1023-02    452
WH-1015-01    438
WH-1015-02    427
WH-1023-01    400
WH-1017-01    248
WH-1013-02    247
WH-1033-01    243
WH-1030-02    236
WH-1011-02    235
WH-1010-01    235
WH-1039-02    234
WH-1013-01    233
WH-1021-02    233
WH-1027-02    233
WH-1041-02    229
WH-1031-01    229
WH-1014-02    228
WH-1028-01    228
WH-1016-02    228
WH-1011-01    227
WH-1033-02    224
WH-1012-02    224
WH-1029-01    222
WH-1034-01    221
WH-1018-02    221
WH-1028-02    220
WH-1036-01    220
WH-1026-02    219
WH-1018-01    219
WH-1043-01    219
WH-1035-01    219
WH-1020-01    218
WH-1024-02    216
WH-1014-01    215
WH-1043-02    213
WH-1032-02    213
WH-1017-02    212
WH-1024-01    211
WH-1042-01    211
WH-1041-01    211
WH-1025-01    210
WH-1031-02    210
WH-1042-02    210
WH-1022-01    208
WH-1022-02    207
WH-1040-02    205
WH-1030-01    205
WH-1037-01    205
WH-1025-02    204
WH-1029-02    203
WH-1020-02    203
WH-1038-01    202
WH-1038-02    201
WH-1026-01    200
WH-1036-02    199
WH-1021-01    199
WH-1040-01    199
WH-1016-01    199
WH-1019-02    198
WH-1034-02    198
WH-1039-01    198
WH-1035-02    198
WH-1032-01    197
WH-1027-01    197
WH-1010-02    197
WH-1037-02    196
WH-1019-01    192
WH-1012-01    188
Name: count, dtype: int64
-----------------------------------


Kolom shipto_desc memiliki 68 kategori unik.
shipto_desc
Gudang Jawa Tengah 02                  452
Gudang Jambi 01                        438
Gudang Jambi 02                        427
Gudang Jawa Tengah 01                  400
Gudang Kepulauan Bangka Belitung 01    248
Gudang Riau 02                         247
Gudang Sulawesi Selatan 01             243
Gudang Kalimantan Selatan 02           236
Gudang Sumatera Utara 02               235
Gudang Aceh 01                         235
Gudang Maluku 02                       234
Gudang Riau 01                         233
Gudang Dki Jakarta 02                  233
Gudang Nusa Tenggara Barat 02          233
Gudang Papua 02                        229
Gudang Kalimantan Tengah 01            229
Gudang Kepulauan Riau 02               228
Gudang Nusa Tenggara Timur 01          228
Gudang Sumatera Selatan 02             228
Gudang Sumatera Utara 01               227
Gudang Sulawesi Selatan 02             224
Gudang Sumatera Barat 02               224
Gudang Kalimantan Barat 01             222
Gudang Sulawesi Barat 01               221
Gudang Bengkulu 02                     221
Gudang Nusa Tenggara Timur 02          220
Gudang Sulawesi Tengah 01              220
Gudang Bali 02                         219
Gudang Bengkulu 01                     219
Gudang Kalimantan Utara 01             219
Gudang Sulawesi Tenggara 01            219
Gudang Banten 01                       218
Gudang Di Yogyakarta 02                216
Gudang Kepulauan Riau 01               215
Gudang Kalimantan Utara 02             213
Gudang Kalimantan Timur 02             213
Gudang Kepulauan Bangka Belitung 02    212
Gudang Di Yogyakarta 01                211
Gudang Papua Barat 01                  211
Gudang Papua 01                        211
Gudang Jawa Timur 01                   210
Gudang Kalimantan Tengah 02            210
Gudang Papua Barat 02                  210
Gudang Jawa Barat 01                   208
Gudang Jawa Barat 02                   207
Gudang Maluku Utara 02                 205
Gudang Kalimantan Selatan 01           205
Gudang Sulawesi Utara 01               205
Gudang Jawa Timur 02                   204
Gudang Kalimantan Barat 02             203
Gudang Banten 02                       203
Gudang Gorontalo 01                    202
Gudang Gorontalo 02                    201
Gudang Bali 01                         200
Gudang Sulawesi Tengah 02              199
Gudang Dki Jakarta 01                  199
Gudang Maluku Utara 01                 199
Gudang Sumatera Selatan 01             199
Gudang Lampung 02                      198
Gudang Sulawesi Barat 02               198
Gudang Maluku 01                       198
Gudang Sulawesi Tenggara 02            198
Gudang Kalimantan Timur 01             197
Gudang Nusa Tenggara Barat 01          197
Gudang Aceh 02                         197
Gudang Sulawesi Utara 02               196
Gudang Lampung 01                      192
Gudang Sumatera Barat 01               188
Name: count, dtype: int64
-----------------------------------


Kolom soldto memiliki 102 kategori unik.
soldto
SD-1015-01    302
SD-1023-02    298
SD-1015-03    293
SD-1023-01    284
SD-1023-03    270
SD-1015-02    270
SD-1031-01    174
SD-1013-03    172
SD-1011-02    168
SD-1017-01    166
SD-1028-01    165
SD-1013-01    161
SD-1010-02    160
SD-1033-01    160
SD-1039-03    160
SD-1040-03    158
SD-1043-01    158
SD-1033-02    157
SD-1028-03    156
SD-1012-01    155
SD-1042-01    154
SD-1030-02    153
SD-1035-01    153
SD-1027-02    153
SD-1018-01    153
SD-1038-03    153
SD-1022-01    151
SD-1026-03    151
SD-1017-03    151
SD-1029-02    151
SD-1033-03    150
SD-1024-02    150
SD-1030-01    150
SD-1041-02    149
SD-1025-01    149
SD-1021-03    149
SD-1039-01    149
SD-1014-01    149
SD-1024-01    148
SD-1034-02    148
SD-1014-03    148
SD-1016-01    148
SD-1011-01    148
SD-1036-02    148
SD-1013-02    147
SD-1032-02    147
SD-1041-01    147
SD-1021-02    146
SD-1029-03    146
SD-1014-02    146
SD-1011-03    146
SD-1018-03    145
SD-1041-03    144
SD-1036-01    143
SD-1017-02    143
SD-1020-02    143
SD-1038-01    143
SD-1034-03    142
SD-1018-02    142
SD-1027-03    142
SD-1037-02    142
SD-1043-02    141
SD-1020-01    141
SD-1016-03    141
SD-1042-02    141
SD-1031-03    140
SD-1035-03    140
SD-1010-01    140
SD-1019-02    139
SD-1016-02    138
SD-1030-03    138
SD-1021-01    137
SD-1026-01    137
SD-1020-03    137
SD-1022-02    136
SD-1037-03    136
SD-1019-03    136
SD-1027-01    135
SD-1012-03    134
SD-1025-02    134
SD-1043-03    133
SD-1032-03    132
SD-1010-03    132
SD-1026-02    131
SD-1025-03    131
SD-1032-01    131
SD-1040-01    130
SD-1024-03    129
SD-1034-01    129
SD-1029-01    128
SD-1022-03    128
SD-1036-03    128
SD-1028-02    127
SD-1042-03    126
SD-1031-02    125
SD-1035-02    124
SD-1037-01    123
SD-1039-02    123
SD-1012-02    123
SD-1040-02    116
SD-1019-01    115
SD-1038-02    107
Name: count, dtype: int64
-----------------------------------


Kolom soldto_desc memiliki 102 kategori unik.
soldto_desc
PT Distributor Jambi 01                        302
PT Distributor Jawa Tengah 02                  298
PT Distributor Jambi 03                        293
PT Distributor Jawa Tengah 01                  284
PT Distributor Jawa Tengah 03                  270
PT Distributor Jambi 02                        270
PT Distributor Kalimantan Tengah 01            174
PT Distributor Riau 03                         172
PT Distributor Sumatera Utara 02               168
PT Distributor Kepulauan Bangka Belitung 01    166
PT Distributor Nusa Tenggara Timur 01          165
PT Distributor Riau 01                         161
PT Distributor Aceh 02                         160
PT Distributor Sulawesi Selatan 01             160
PT Distributor Maluku 03                       160
PT Distributor Maluku Utara 03                 158
PT Distributor Kalimantan Utara 01             158
PT Distributor Sulawesi Selatan 02             157
PT Distributor Nusa Tenggara Timur 03          156
PT Distributor Sumatera Barat 01               155
PT Distributor Papua Barat 01                  154
PT Distributor Kalimantan Selatan 02           153
PT Distributor Sulawesi Tenggara 01            153
PT Distributor Nusa Tenggara Barat 02          153
PT Distributor Bengkulu 01                     153
PT Distributor Gorontalo 03                    153
PT Distributor Jawa Barat 01                   151
PT Distributor Bali 03                         151
PT Distributor Kepulauan Bangka Belitung 03    151
PT Distributor Kalimantan Barat 02             151
PT Distributor Sulawesi Selatan 03             150
PT Distributor Di Yogyakarta 02                150
PT Distributor Kalimantan Selatan 01           150
PT Distributor Papua 02                        149
PT Distributor Jawa Timur 01                   149
PT Distributor Dki Jakarta 03                  149
PT Distributor Maluku 01                       149
PT Distributor Kepulauan Riau 01               149
PT Distributor Di Yogyakarta 01                148
PT Distributor Sulawesi Barat 02               148
PT Distributor Kepulauan Riau 03               148
PT Distributor Sumatera Selatan 01             148
PT Distributor Sumatera Utara 01               148
PT Distributor Sulawesi Tengah 02              148
PT Distributor Riau 02                         147
PT Distributor Kalimantan Timur 02             147
PT Distributor Papua 01                        147
PT Distributor Dki Jakarta 02                  146
PT Distributor Kalimantan Barat 03             146
PT Distributor Kepulauan Riau 02               146
PT Distributor Sumatera Utara 03               146
PT Distributor Bengkulu 03                     145
PT Distributor Papua 03                        144
PT Distributor Sulawesi Tengah 01              143
PT Distributor Kepulauan Bangka Belitung 02    143
PT Distributor Banten 02                       143
PT Distributor Gorontalo 01                    143
PT Distributor Sulawesi Barat 03               142
PT Distributor Bengkulu 02                     142
PT Distributor Nusa Tenggara Barat 03          142
PT Distributor Sulawesi Utara 02               142
PT Distributor Kalimantan Utara 02             141
PT Distributor Banten 01                       141
PT Distributor Sumatera Selatan 03             141
PT Distributor Papua Barat 02                  141
PT Distributor Kalimantan Tengah 03            140
PT Distributor Sulawesi Tenggara 03            140
PT Distributor Aceh 01                         140
PT Distributor Lampung 02                      139
PT Distributor Sumatera Selatan 02             138
PT Distributor Kalimantan Selatan 03           138
PT Distributor Dki Jakarta 01                  137
PT Distributor Bali 01                         137
PT Distributor Banten 03                       137
PT Distributor Jawa Barat 02                   136
PT Distributor Sulawesi Utara 03               136
PT Distributor Lampung 03                      136
PT Distributor Nusa Tenggara Barat 01          135
PT Distributor Sumatera Barat 03               134
PT Distributor Jawa Timur 02                   134
PT Distributor Kalimantan Utara 03             133
PT Distributor Kalimantan Timur 03             132
PT Distributor Aceh 03                         132
PT Distributor Bali 02                         131
PT Distributor Jawa Timur 03                   131
PT Distributor Kalimantan Timur 01             131
PT Distributor Maluku Utara 01                 130
PT Distributor Di Yogyakarta 03                129
PT Distributor Sulawesi Barat 01               129
PT Distributor Kalimantan Barat 01             128
PT Distributor Jawa Barat 03                   128
PT Distributor Sulawesi Tengah 03              128
PT Distributor Nusa Tenggara Timur 02          127
PT Distributor Papua Barat 03                  126
PT Distributor Kalimantan Tengah 02            125
PT Distributor Sulawesi Tenggara 02            124
PT Distributor Sulawesi Utara 01               123
PT Distributor Maluku 02                       123
PT Distributor Sumatera Barat 02               123
PT Distributor Maluku Utara 02                 116
PT Distributor Lampung 01                      115
PT Distributor Gorontalo 02                    107
Name: count, dtype: int64
-----------------------------------


Kolom plant memiliki 5 kategori unik.
plant
PL-005    6384
PL-001    3088
PL-003    2595
PL-004    2109
PL-002    1263
Name: count, dtype: int64
-----------------------------------


Kolom plant_name memiliki 5 kategori unik.
plant_name
Pabrik Pangkep     6384
Pabrik Indarung    3088
Pabrik Narogong    2595
Pabrik Tuban       2109
Pabrik Baturaja    1263
Name: count, dtype: int64
-----------------------------------


Kolom area_name memiliki 49 kategori unik.
area_name
AREA 72 MAKASSAR        467
AREA 28 BANGKA BLTNG    460
AREA 90 KUPANG          448
AREA 18 JAMBI           443
AREA 65 BANJARMASIN     441
AREA 95 JAYAPURA        440
AREA 01 BANDA ACEH      432
AREA 70 TARAKAN         432
AREA 92 MALUKU          432
AREA 34 JAKARTA         432
AREA 86 LOMBOK          430
AREA 47 YOGYAKARTA      427
AREA 58 PONTIANAK       425
AREA 19 MUARO JAMBI     422
AREA 93 MANOKWARI       421
AREA 33 BANTEN          421
AREA 81 PALU            419
AREA 57 DENPASAR        419
AREA 79 KENDARI         417
AREA 91 MALUKU UTARA    404
AREA 83 GORONTALO       403
AREA 85 MINAHASA        401
AREA 45 SOLO            298
AREA 63 PALANGKARAYA    291
AREA 75 POLEWALI MDR    289
AREA 17 KEP. RIAU       287

#### Table Sell Out

In [32]:
check_categorical_value(table_sell_out)

Kolom provinsi memiliki 34 kategori unik.
provinsi
JAMBI                        2929
JAWA TENGAH                  2896
NUSA TENGGARA BARAT          1845
ACEH                         1826
KALIMANTAN UTARA             1803
SULAWESI SELATAN             1758
KALIMANTAN TIMUR             1756
RIAU                         1747
KEPULAUAN RIAU               1725
JAWA TIMUR                   1636
PAPUA                        1624
BANTEN                       1596
BALI                         1575
KALIMANTAN TENGAH            1482
KALIMANTAN SELATAN           1449
BENGKULU                     1442
MALUKU                       1407
SUMATERA UTARA               1388
MALUKU UTARA                 1334
NUSA TENGGARA TIMUR          1278
SULAWESI TENGAH              1220
SUMATERA SELATAN             1208
PAPUA BARAT                  1198
DI YOGYAKARTA                1187
GORONTALO                    1146
SULAWESI TENGGARA            1098
SUMATERA BARAT               1073
KALIMANTAN BARAT             1068
LAMPUNG                      1022
SULAWESI BARAT                996
DKI JAKARTA                   939
KEPULAUAN BANGKA BELITUNG     889
JAWA BARAT                    870
SULAWESI UTARA                757
Name: count, dtype: int64
-----------------------------------


Kolom kode_toko memiliki 383 kategori unik.
kode_toko
TK-WH-1023-01-2    255
TK-WH-1023-02-8    254
TK-WH-1023-02-6    248
TK-WH-1023-02-1    248
TK-WH-1023-02-4    247
TK-WH-1015-02-5    242
TK-WH-1023-01-3    240
TK-WH-1023-02-3    240
TK-WH-1023-02-2    238
TK-WH-1015-02-6    237
TK-WH-1023-02-7    236
TK-WH-1023-02-5    235
TK-WH-1015-01-2    231
TK-WH-1015-01-3    231
TK-WH-1015-02-7    229
TK-WH-1023-01-4    228
TK-WH-1023-01-1    227
TK-WH-1015-01-6    227
TK-WH-1015-01-4    226
TK-WH-1015-01-1    225
TK-WH-1015-02-2    222
TK-WH-1015-01-5    219
TK-WH-1015-02-4    216
TK-WH-1015-02-1    216
TK-WH-1015-02-3    208
TK-WH-1017-01-3    162
TK-WH-1017-01-2    162
TK-WH-1018-01-2    156
TK-WH-1013-02-3    154
TK-WH-1013-02-6    150
TK-WH-1029-01-3    150
TK-WH-1028-01-2    149
TK-WH-1017-01-1    149
TK-WH-1016-02-4    148
TK-WH-1035-01-2    146
TK-WH-1035-01-1    146
TK-WH-1017-02-3    145
TK-WH-1039-02-1    144
TK-WH-1018-01-1    143
TK-WH-1016-02-3    143
TK-WH-1018-01-3    143
TK-WH-1021-02-2    142
TK-WH-1022-01-3    141
TK-WH-1012-02-1    141
TK-WH-1024-02-3    141
TK-WH-1017-02-2    141
TK-WH-1012-02-5    140
TK-WH-1012-02-4    140
TK-WH-1033-01-5    139
TK-WH-1021-02-4    139
TK-WH-1028-01-3    139
TK-WH-1029-01-1    139
TK-WH-1034-01-4    139
TK-WH-1013-02-1    139
TK-WH-1028-01-1    139
TK-WH-1034-01-2    138
TK-WH-1013-01-2    138
TK-WH-1011-01-4    138
TK-WH-1036-01-1    137
TK-WH-1030-02-1    137
TK-WH-1039-02-5    137
TK-WH-1014-02-7    136
TK-WH-1012-02-2    136
TK-WH-1028-02-7    136
TK-WH-1021-02-3    136
TK-WH-1021-02-1    136
TK-WH-1039-02-2    136
TK-WH-1033-01-1    136
TK-WH-1012-01-3    135
TK-WH-1018-02-5    135
TK-WH-1022-01-2    135
TK-WH-1043-02-6    134
TK-WH-1036-01-4    134
TK-WH-1013-02-2    134
TK-WH-1014-02-8    134
TK-WH-1016-02-1    133
TK-WH-1030-02-6    133
TK-WH-1013-02-4    133
TK-WH-1011-01-5    133
TK-WH-1013-01-1    133
TK-WH-1025-01-4    133
TK-WH-1010-01-4    133
TK-WH-1029-01-2    132
TK-WH-1014-02-2    132
TK-WH-1033-01-3    132
TK-WH-1033-01-2    132
TK-WH-1032-01-7    132
TK-WH-1030-02-2    132
TK-WH-1016-02-2    132
TK-WH-1035-01-3    132
TK-WH-1021-01-3    131
TK-WH-1042-01-4    131
TK-WH-1034-01-1    131
TK-WH-1012-02-3    131
TK-WH-1013-02-5    131
TK-WH-1039-02-4    131
TK-WH-1010-01-5    131
TK-WH-1038-01-1    131
TK-WH-1018-02-6    130
TK-WH-1010-01-2    130
TK-WH-1011-01-3    130
TK-WH-1017-02-1    130
TK-WH-1013-01-5    130
TK-WH-1011-02-5    129
TK-WH-1019-01-3    129
TK-WH-1036-01-2    129
TK-WH-1024-02-2    129
TK-WH-1037-01-3    129
TK-WH-1018-02-8    129
TK-WH-1013-01-3    129
TK-WH-1031-02-2    129
TK-WH-1025-01-3    129
TK-WH-1031-02-6    129
TK-WH-1043-02-8    129
TK-WH-1043-02-1    129
TK-WH-1042-01-3    129
TK-WH-1027-02-8    128
TK-WH-1024-02-1    128
TK-WH-1030-02-3    128
TK-WH-1028-02-2    128
TK-WH-1038-01-3    128
TK-WH-1010-01-3    128
TK-WH-1021-01-2    128
TK-WH-1013-01-4    128
TK-WH-1031-02-5    128
TK-WH-1040-02-3    128
TK-WH-1014-02-5    128
TK-WH-1031-01-1    128
TK-WH-1034-01-3    127
TK-WH-1039-02-3    127
TK-WH-1030-02-4    127
TK-WH-1033-01-4    127
TK-WH-1021-01-1    127
TK-WH-1037-01-2    127
TK-WH-1037-02-2    127
TK-WH-1037-02-3    127
TK-WH-1034-02-3    127
TK-WH-1026-02-4    127
TK-WH-1013-02-7    127
TK-WH-1032-02-2    127
TK-WH-1041-02-1    127
TK-WH-1011-01-2    127
TK-WH-1033-02-7    127
TK-WH-1011-02-1    127
TK-WH-1032-02-7    127
TK-WH-1010-01-6    127
TK-WH-1032-02-8    127
TK-WH-1037-02-1    126
TK-WH-1025-01-1    126
TK-WH-1036-01-3    126
TK-WH-1031-02-3    126
TK-WH-1026-02-7    126
TK-WH-1027-02-7    126
TK-WH-1042-01-1    126
TK-WH-1033-01-6    126
TK-WH-1028-02-4    126
TK-WH-1027-02-5    126
TK-WH-1011-02-4    126
TK-WH-1011-02-6    126
TK-WH-1014-01-6    126
TK-WH-1012-01-2    126
TK-WH-1025-01-2    126
TK-WH-1031-02-1    125
TK-WH-1014-02-3    125
TK-WH-1036-02-3    125
TK-WH-1025-01-7    125
TK-WH-1030-02-5    124
TK-WH-1018-02-4    124
TK-WH-1025-01-5    124
TK-WH-1012-01-1    124
TK-WH-1022-01-1    124
TK-WH-1019-02-2    124
TK-WH-1014-02-6    124
TK-WH-1042-01-2    124
TK-WH-1043-01-4    124
TK-WH-1031-01-3    124
TK-WH-1032-01-2    123
TK-WH-1026-02-5    123
TK-WH-1018-02-7    123
TK-WH-1033-02-2    123
TK-WH-1033-02-5    123
TK-WH-1019-01-2    123
TK-WH-1031-01-2    123
TK-WH-1043-01-5    123
TK-WH-1028-02-1    122
TK-WH-1026-02-3    122
TK-WH-1031-01-4    122
TK-WH-1043-01-6    122
TK-WH-1022-02-1    122
TK-WH-1027-02-1    122
TK-WH-1036-02-5    122
TK-WH-1014-01-3    122
TK-WH-1014-02-1    122
TK-WH-1024-01-7    122
TK-WH-1027-02-2    122
TK-WH-1033-02-1    122
TK-WH-1042-02-4    122
TK-WH-1018-02-1    121
TK-WH-1020-02-4    121
TK-WH-1031-02-4    121
TK-WH-1013-01-6    121
TK-WH-1010-01-1    121
TK-WH-1020-02-2    121
TK-WH-1027-02-6    121
TK-WH-1020-02-1    121
TK-WH-1014-02-4    121
TK-WH-1011-02-3    121
TK-WH-1043-02-7    121
TK-WH-1037-01-1    121
TK-WH-1041-02-3    121
TK-WH-1025-02-2    120
TK-WH-1040-02-1    120
TK-WH-1029-02-6    120
TK-WH-1041-02-5    120
TK-WH-1020-01-3    120
TK-WH-1027-01-1    120
TK-WH-1034-02-1    119
TK-WH-1018-02-3    119
TK-WH-1010-01-8    119
TK-WH-1014-01-5    119
TK-WH-1033-02-6    119
TK-WH-1027-02-3    119
TK-WH-1043-02-5    119
TK-WH-1043-02-4    119
TK-WH-1035-02-5    119
TK-WH-1018-02-2    119
TK-WH-1033-02-4    118
TK-WH-1043-02-3    118
TK-WH-1025-02-5    118
TK-WH-1042-02-1    118
TK-WH-1028-02-5    118
TK-WH-1041-02-7    118
TK-WH-1025-01-6    118
TK-WH-1040-02-5    118
TK-WH-1010-01-7    118
TK-WH-1041-01-5    118
TK-WH-1011-02-2    117
TK-WH-1038-02-6    117
TK-WH-1033-02-8    117
TK-WH-1035-02-2    117
TK-WH-1032-02-3    117
TK-WH-1016-01-2    117
TK-WH-1041-01-3    117
TK-WH-1030-01-6    117
TK-WH-1033-02-3    117
TK-WH-1041-02-6    117
TK-WH-1027-02-4    117
TK-WH-1026-02-2    117
TK-WH-1036-02-2    117
TK-WH-1032-02-6    116
TK-WH-1041-01-6    116
TK-WH-1041-01-4    116
TK-WH-1020-01-6    116
TK-WH-1040-02-4    116
TK-WH-1036-02-4    116
TK-WH-1022-02-2    116
TK-WH-1022-02-3    116
TK-WH-1022-02-4    116
TK-WH-1043-01-1    116
TK-WH-1020-01-5    116
TK-WH-1031-01-6    115
TK-WH-1020-01-4    115
TK-WH-1020-01-1    115
TK-WH-1042-02-5    115
TK-WH-1030-01-1    115
TK-WH-1032-02-5    115
TK-WH-1040-02-2    115
TK-WH-1032-01-5    115
TK-WH-1014-01-2    115
TK-WH-1026-02-6    115
TK-WH-1041-02-8    115
TK-WH-1038-01-2    114
TK-WH-1019-01-1    114
TK-WH-1020-02-8    114
TK-WH-1043-01-7    114
TK-WH-1032-01-6    114
TK-WH-1041-01-2    114
TK-WH-1011-01-1    114
TK-WH-1038-02-3    114
TK-WH-1024-01-5    114
TK-WH-1042-02-3    114
TK-WH-1032-02-4    114
TK-WH-1030-01-2    113
TK-WH-1035-02-4    113
TK-WH-1026-02-1    113
TK-WH-1024-01-2    113
TK-WH-1041-02-2    113
TK-WH-1032-02-1    113
TK-WH-1035-02-6    113
TK-WH-1043-01-3    113
TK-WH-1020-02-5    113
TK-WH-1016-01-6    113
TK-WH-1042-02-6    112
TK-WH-1040-01-1    112
TK-WH-1028-02-6    112
TK-WH-1027-01-8    112
TK-WH-1014-01-4    112
TK-WH-1024-01-1    112
TK-WH-1025-02-7    112
TK-WH-1031-01-5    112
TK-WH-1043-02-2    112
TK-WH-1024-01-4    112
TK-WH-1029-02-3    111
TK-WH-1030-01-3    111
TK-WH-1032-01-1    111
TK-WH-1038-02-1    111
TK-WH-1027-01-4    111
TK-WH-1020-02-7    111
TK-WH-1020-01-2    111
TK-WH-1038-02-2    111
TK-WH-1036-02-1    110
TK-WH-1035-02-1    110
TK-WH-1029-02-2    110
TK-WH-1043-01-2    110
TK-WH-1030-01-5    109
TK-WH-1026-01-3    109
TK-WH-1014-01-1    109
TK-WH-1039-01-3    109
TK-WH-1024-01-3    109
TK-WH-1028-02-3    109
TK-WH-1034-02-4    108
TK-WH-1040-01-2    108
TK-WH-1038-02-4    108
TK-WH-1019-02-4    108
TK-WH-1019-02-5    108
TK-WH-1041-02-4    108
TK-WH-1025-02-6    108
TK-WH-1040-01-6    108
TK-WH-1038-02-7    108
TK-WH-1026-01-4    107
TK-WH-1034-02-2    107
TK-WH-1039-01-5    107
TK-WH-1029-02-4    107
TK-WH-1019-02-3    107
TK-WH-1042-02-2    107
TK-WH-1026-01-1    107
TK-WH-1024-01-6    107
TK-WH-1027-01-2    106
TK-WH-1010-02-5    106
TK-WH-1039-01-2    106
TK-WH-1040-01-3    106
TK-WH-1027-01-5    106
TK-WH-1039-01-6    106
TK-WH-1016-01-4    106
TK-WH-1016-01-3    106
TK-WH-1019-02-6    106
TK-WH-1016-01-5    105
TK-WH-1027-01-6    105
TK-WH-1040-01-5    105
TK-WH-1016-01-1    105
TK-WH-1025-02-1    105
TK-WH-1010-02-4    105
TK-WH-1039-01-7    105
TK-WH-1041-01-1    104
TK-WH-1036-02-6    104
TK-WH-1026-01-7    104
TK-WH-1038-02-5    104
TK-WH-1040-01-4    104
TK-WH-1032-01-4    104
TK-WH-1010-02-2    104
TK-WH-1010-02-7    103
TK-WH-1030-01-4    103
TK-WH-1019-02-1    103
TK-WH-1027-01-7    103
TK-WH-1026-01-2    102
TK-WH-1020-02-6    102
TK-WH-1010-02-6    102
TK-WH-1026-01-6    102
TK-WH-1035-02-3    102
TK-WH-1025-02-3    102
TK-WH-1010-02-8    102
TK-WH-1032-01-3    101
TK-WH-1029-02-1    101
TK-WH-1026-01-5    101
TK-WH-1027-01-3    101
TK-WH-1020-02-3    100
TK-WH-1039-01-1    100
TK-WH-1039-01-4     99
TK-WH-1010-02-3     99
TK-WH-1029-02-5     98
TK-WH-1010-02-1     98
TK-WH-1040-01-7     94
TK-WH-1025-02-4     90
Name: count, dtype: int64
-----------------------------------


Kolom nama_toko memiliki 62 kategori unik.
nama_toko
TB Sejahtera 1    1900
TB Jaya 1         1870
TB Sejahtera 3    1819
TB Sejahtera 5    1650
TB Jaya 4         1543
TB Makmur 2       1469
TB Sentosa 2      1418
TB Abadi 4        1374
TB Jaya 3         1329
TB Abadi 2        1318
TB Sejahtera 2    1281
TB Berkah 4       1221
TB Jaya 7         1188
TB Maju 3         1142
TB Berkah 3       1132
TB Berkah 6       1061
TB Abadi 3        1060
TB Nusantara 1     995
TB Berkah 2        971
TB Sentosa 3       942
TB Nusantara 2     866
TB Makmur 3        857
TB Abadi 5         850
TB Berkah 1        844
TB Abadi 1         825
TB Makmur 6        823
TB Abadi 6         819
TB Sentosa 5       816
TB Sentosa 1       813
TB Maju 2          797
TB Maju 1          782
TB Jaya 2          746
TB Nusantara 6     725
TB Nusantara 4     725
TB Sejahtera 4     719
TB Makmur 1        717
TB Sejahtera 6     694
TB Maju 6          687
TB Maju 5          683
TB Berkah 5        594
TB Sentosa 4       590
TB Maju 7          573
TB Nusantara 3     526
TB Jaya 5          499
TB Makmur 7        470
TB Makmur 4        455
TB Maju 8          374
TB Makmur 5        373
TB Abadi 7         372
TB Makmur 8        369
TB Sentosa 6       367
TB Nusantara 5     355
TB Maju 4          257
TB Sentosa 8       246
TB Berkah 7        243
TB Jaya 8          216
TB Sentosa 7       211
TB Berkah 8        129
TB Sejahtera 8     127
TB Nusantara 7     126
TB Abadi 8         119
TB Jaya 6          105
Name: count, dtype: int64
-----------------------------------


Kolom kode_gudang memiliki 68 kategori unik.
kode_gudang
WH-1023-02    1946
WH-1015-02    1570
WH-1015-01    1359
WH-1014-02    1022
WH-1010-01    1007
WH-1018-02    1000
WH-1043-02     981
WH-1027-02     981
WH-1013-02     968
WH-1033-02     966
WH-1032-02     956
WH-1023-01     950
WH-1041-02     939
WH-1020-02     903
WH-1025-01     881
WH-1027-01     864
WH-1028-02     851
WH-1026-02     843
WH-1043-01     822
WH-1010-02     819
WH-1032-01     800
WH-1033-01     792
WH-1024-01     789
WH-1030-02     781
WH-1013-01     779
WH-1038-02     773
WH-1031-02     758
WH-1025-02     755
WH-1011-02     746
WH-1040-01     737
WH-1039-01     732
WH-1026-01     732
WH-1031-01     724
WH-1014-01     703
WH-1036-02     694
WH-1020-01     693
WH-1042-02     688
WH-1012-02     688
WH-1041-01     685
WH-1039-02     675
WH-1035-02     674
WH-1030-01     668
WH-1019-02     656
WH-1016-01     652
WH-1029-02     647
WH-1011-01     642
WH-1040-02     597
WH-1016-02     556
WH-1021-02     553
WH-1034-01     535
WH-1036-01     526
WH-1042-01     510
WH-1017-01     473
WH-1022-02     470
WH-1034-02     461
WH-1018-01     442
WH-1028-01     427
WH-1035-01     424
WH-1029-01     421
WH-1017-02     416
WH-1022-01     400
WH-1024-02     398
WH-1021-01     386
WH-1012-01     385
WH-1037-02     380
WH-1037-01     377
WH-1038-01     373
WH-1019-01     366
Name: count, dtype: int64
-----------------------------------


Kolom nama_gudang memiliki 68 kategori unik.
nama_gudang
Gudang Jawa Tengah 02                  1946
Gudang Jambi 02                        1570
Gudang Jambi 01                        1359
Gudang Kepulauan Riau 02               1022
Gudang Aceh 01                         1007
Gudang Bengkulu 02                     1000
Gudang Kalimantan Utara 02              981
Gudang Nusa Tenggara Barat 02           981
Gudang Riau 02                          968
Gudang Sulawesi Selatan 02              966
Gudang Kalimantan Timur 02              956
Gudang Jawa Tengah 01                   950
Gudang Papua 02                         939
Gudang Banten 02                        903
Gudang Jawa Timur 01                    881
Gudang Nusa Tenggara Barat 01           864
Gudang Nusa Tenggara Timur 02           851
Gudang Bali 02                          843
Gudang Kalimantan Utara 01              822
Gudang Aceh 02                          819
Gudang Kalimantan Timur 01              800
Gudang Sulawesi Selatan 01              792
Gudang Di Yogyakarta 01                 789
Gudang Kalimantan Selatan 02            781
Gudang Riau 01                          779
Gudang Gorontalo 02                     773
Gudang Kalimantan Tengah 02             758
Gudang Jawa Timur 02                    755
Gudang Sumatera Utara 02                746
Gudang Maluku Utara 01                  737
Gudang Maluku 01                        732
Gudang Bali 01                          732
Gudang Kalimantan Tengah 01             724
Gudang Kepulauan Riau 01                703
Gudang Sulawesi Tengah 02               694
Gudang Banten 01                        693
Gudang Papua Barat 02                   688
Gudang Sumatera Barat 02                688
Gudang Papua 01                         685
Gudang Maluku 02                        675
Gudang Sulawesi Tenggara 02             674
Gudang Kalimantan Selatan 01            668
Gudang Lampung 02                       656
Gudang Sumatera Selatan 01              652
Gudang Kalimantan Barat 02              647
Gudang Sumatera Utara 01                642
Gudang Maluku Utara 02                  597
Gudang Sumatera Selatan 02              556
Gudang Dki Jakarta 02                   553
Gudang Sulawesi Barat 01                535
Gudang Sulawesi Tengah 01               526
Gudang Papua Barat 01                   510
Gudang Kepulauan Bangka Belitung 01     473
Gudang Jawa Barat 02                    470
Gudang Sulawesi Barat 02                461
Gudang Bengkulu 01                      442
Gudang Nusa Tenggara Timur 01           427
Gudang Sulawesi Tenggara 01             424
Gudang Kalimantan Barat 01              421
Gudang Kepulauan Bangka Belitung 02     416
Gudang Jawa Barat 01                    400
Gudang Di Yogyakarta 02                 398
Gudang Dki Jakarta 01                   386
Gudang Sumatera Barat 01                385
Gudang Sulawesi Utara 02                380
Gudang Sulawesi Utara 01                377
Gudang Gorontalo 01                     373
Gudang Lampung 01                       366
Name: count, dtype: int64
-----------------------------------


Kolom kode_distributor memiliki 102 kategori unik.
kode_distributor
SD-1015-03    1020
SD-1023-02    1007
SD-1023-01     993
SD-1015-01     977
SD-1015-02     932
SD-1023-03     896
SD-1032-02     672
SD-1010-02     654
SD-1025-01     629
SD-1027-02     628
SD-1013-03     626
SD-1027-03     621
SD-1043-01     611
SD-1033-01     610
SD-1027-01     596
SD-1043-02     596
SD-1043-03     596
SD-1014-01     595
SD-1010-01     594
SD-1033-02     589
SD-1031-01     586
SD-1010-03     578
SD-1041-02     572
SD-1014-03     571
SD-1026-03     568
SD-1013-01     565
SD-1014-02     559
SD-1033-03     559
SD-1013-02     556
SD-1032-03     554
SD-1041-01     552
SD-1020-01     551
SD-1020-03     537
SD-1032-01     530
SD-1026-01     525
SD-1039-03     524
SD-1030-02     517
SD-1025-02     512
SD-1040-03     509
SD-1020-02     508
SD-1018-01     504
SD-1041-03     500
SD-1025-03     495
SD-1030-01     489
SD-1039-01     489
SD-1018-03     489
SD-1026-02     482
SD-1031-03     480
SD-1028-01     478
SD-1011-03     471
SD-1011-02     471
SD-1024-02     467
SD-1038-03     452
SD-1018-02     449
SD-1011-01     446
SD-1030-03     443
SD-1040-01     431
SD-1028-03     428
SD-1036-02     423
SD-1042-02     417
SD-1031-02     416
SD-1016-02     413
SD-1012-01     413
SD-1042-01     408
SD-1036-01     404
SD-1016-01     400
SD-1035-01     400
SD-1016-03     395
SD-1029-02     394
SD-1040-02     394
SD-1039-02     394
SD-1036-03     393
SD-1019-02     390
SD-1038-01     388
SD-1024-01     379
SD-1042-03     373
SD-1028-02     372
SD-1035-03     364
SD-1029-03     358
SD-1012-03     351
SD-1019-03     347
SD-1034-02     346
SD-1024-03     341
SD-1034-03     341
SD-1035-02     334
SD-1021-03     332
SD-1017-01     320
SD-1029-01     316
SD-1022-01     316
SD-1034-01     309
SD-1012-02     309
SD-1038-02     306
SD-1021-01     305
SD-1021-02     302
SD-1022-02     293
SD-1017-03     288
SD-1019-01     285
SD-1017-02     281
SD-1037-02     279
SD-1022-03     261
SD-1037-03     240
SD-1037-01     238
Name: count, dtype: int64
-----------------------------------


Kolom kabupaten_gudang memiliki 81 kategori unik.
kabupaten_gudang
KOTA JAMBI                      1535
KABUPATEN MUARO JAMBI           1394
KOTA SEMARANG                    998
KOTA SURAKARTA                   986
KOTA BANDA ACEH                  984
KABUPATEN LOMBOK BARAT           966
KABUPATEN KAMPAR                 960
KABUPATEN BULUNGAN               923
KABUPATEN BANYUMAS               912
KABUPATEN MAROS                  910
KOTA TARAKAN                     880
KABUPATEN BADUNG                 879
KOTA MATARAM                     879
KOTA MAKASSAR                    848
KABUPATEN ACEH BESAR             842
KOTA JAYAPURA                    832
KABUPATEN REJANG LEBONG          815
KABUPATEN JAYAPURA               792
KOTA PEKANBARU                   787
KABUPATEN MALUKU TENGAH          744
KABUPATEN DELI SERDANG           697
KOTA DENPASAR                    696
KOTA MEDAN                       691
KABUPATEN HALMAHERA UTARA        685
KOTA AMBON                       663
KOTA KUPANG                      651
KOTA TERNATE                     649
KABUPATEN KUPANG                 627
KOTA BENGKULU                    627
KOTA PALEMBANG                   622
KOTA PALU                        617
KOTA SORONG                      615
KOTA BATAM                       607
KOTA SAMARINDA                   604
KABUPATEN POSO                   603
KOTA BALIKPAPAN                  600
KABUPATEN MUARA ENIM             586
KABUPATEN MANOKWARI              583
KOTA SERANG                      580
KOTA GORONTALO                   578
KABUPATEN BINTAN                 576
KABUPATEN GORONTALO              568
KABUPATEN KONAWE                 561

#### Table CA

In [33]:
check_categorical_value(table_CA)

Kolom brands_Fondalit memiliki 9 kategori unik.
brands_Fondalit
Atlas         6350
TerraBlock    1561
Fonda         1519
Monolith      1259
Primebase     1063
Vanguard      1041
Tecton         881
Omnicore       859
Kinetiq        850
Name: count, dtype: int64
-----------------------------------


Kolom source memiliki 1 kategori unik.
source
CA    15383
Name: count, dtype: int64
-----------------------------------


Kolom nama_gudang memiliki 68 kategori unik.
nama_gudang
Gudang Jawa Tengah 02                  452
Gudang Jambi 01                        437
Gudang Jambi 02                        426
Gudang Jawa Tengah 01                  400
Gudang Kepulauan Bangka Belitung 01    247
Gudang Riau 02                         246
Gudang Sulawesi Selatan 01             240
Gudang Kalimantan Selatan 02           235
Gudang Aceh 01                         235
Gudang Sumatera Utara 02               233
Gudang Maluku 02                       233
Gudang Nusa Tenggara Barat 02          233
Gudang Riau 01                         232
Gudang Dki Jakarta 02                  232
Gudang Kalimantan Tengah 01            229
Gudang Sumatera Selatan 02             228
Gudang Kepulauan Riau 02               228
Gudang Sumatera Utara 01               227
Gudang Nusa Tenggara Timur 01          227
Gudang Papua 02                        227
Gudang Sulawesi Selatan 02             224
Gudang Sumatera Barat 02               224
Gudang Kalimantan Barat 01             222
Gudang Nusa Tenggara Timur 02          220
Gudang Bali 02                         219
Gudang Sulawesi Tengah 01              219
Gudang Bengkulu 01                     219
Gudang Bengkulu 02                     218
Gudang Banten 01                       218
Gudang Sulawesi Barat 01               217
Gudang Kalimantan Utara 01             217
Gudang Sulawesi Tenggara 01            216
Gudang Di Yogyakarta 02                216
Gudang Kepulauan Riau 01               215
Gudang Kalimantan Timur 02             213
Gudang Kepulauan Bangka Belitung 02    211
Gudang Papua 01                        211
Gudang Papua Barat 01                  210
Gudang Di Yogyakarta 01                210
Gudang Kalimantan Utara 02             210
Gudang Kalimantan Tengah 02            210
Gudang Jawa Timur 01                   209
Gudang Papua Barat 02                  208
Gudang Jawa Barat 01                   208
Gudang Jawa Barat 02                   207
Gudang Maluku Utara 02                 205
Gudang Sulawesi Utara 01               204
Gudang Jawa Timur 02                   204
Gudang Kalimantan Selatan 01           203
Gudang Kalimantan Barat 02             203
Gudang Banten 02                       203
Gudang Gorontalo 01                    201
Gudang Gorontalo 02                    200
Gudang Sumatera Selatan 01             199
Gudang Dki Jakarta 01                  198
Gudang Sulawesi Tenggara 02            198
Gudang Maluku 01                       198
Gudang Sulawesi Tengah 02              198
Gudang Sulawesi Barat 02               198
Gudang Kalimantan Timur 01             197
Gudang Maluku Utara 01                 197
Gudang Aceh 02                         197
Gudang Lampung 02                      196
Gudang Bali 01                         196
Gudang Sulawesi Utara 02               196
Gudang Nusa Tenggara Barat 01          195
Gudang Lampung 01                      192
Gudang Sumatera Barat 01               187
Name: count, dtype: int64
-----------------------------------


Kolom area memiliki 5 kategori unik.
area
AREA 5    6350
AREA 1    3080
AREA 3    2590
AREA 4    2104
AREA 2    1259
Name: count, dtype: int64
-----------------------------------


Kolom provinsi memiliki 34 kategori unik.
provinsi
JAMBI                        863
JAWA TENGAH                  852
RIAU                         478
SULAWESI SELATAN             464
SUMATERA UTARA               460
KEPULAUAN BANGKA BELITUNG    458
NUSA TENGGARA TIMUR          447
KEPULAUAN RIAU               443
KALIMANTAN TENGAH            439
PAPUA                        438
KALIMANTAN SELATAN           438
BENGKULU                     437
ACEH                         432
MALUKU                       431
DKI JAKARTA                  430
NUSA TENGGARA BARAT          428
SUMATERA SELATAN             427
KALIMANTAN UTARA             427
DI YOGYAKARTA                426
KALIMANTAN BARAT             425
BANTEN                       421
PAPUA BARAT                  418
SULAWESI TENGAH              417
JAWA BARAT                   415
SULAWESI BARAT               415
BALI                         415
SULAWESI TENGGARA            414
JAWA TIMUR                   413
SUMATERA BARAT               411
KALIMANTAN TIMUR             410
MALUKU UTARA                 402
GORONTALO                    401
SULAWESI UTARA               400
LAMPUNG                      388
Name: count, dtype: int64
-----------------------------------


Kolom kabupaten memiliki 81 kategori unik.
kabupaten
KOTA JAMBI                      442
KABUPATEN MUARO JAMBI           421
KOTA SURAKARTA                  298
KOTA SEMARANG                   284
KABUPATEN BANYUMAS              270
KABUPATEN KAMPAR                256
KABUPATEN MAROS                 244
KABUPATEN REJANG LEBONG         241
KABUPATEN DELI SERDANG          238
KABUPATEN BANGKA                237
KABUPATEN BADUNG                230
KABUPATEN LOMBOK BARAT          228
KABUPATEN MALUKU TENGAH         228
KABUPATEN KUPANG                224
KOTA JAYAPURA                   223
KOTA KUPANG                     223
KOTA BANDA ACEH                 222
KOTA MEDAN                      222
KOTA PEKANBARU                  222
KOTA PANGKAL PINANG             221
KOTA PALEMBANG                  221
KABUPATEN BULUNGAN              220
KOTA MAKASSAR                   220
KABUPATEN KUBU RAYA             218
KOTA SORONG                     217
KABUPATEN JAYAPURA              215
KABUPATEN KONAWE                210
KABUPATEN ACEH BESAR            210
KABUPATEN POSO                  209
KOTA PALU                       208
KOTA TARAKAN                    207
KOTA PONTIANAK                  207
KABUPATEN HALMAHERA UTARA       207
KOTA MANADO                     206
KABUPATEN MUARA ENIM            206
KOTA KENDARI                    204
KOTA AMBON                      203
KOTA GORONTALO                  203
KABUPATEN MANOKWARI             201
KOTA MATARAM                    200
KABUPATEN GORONTALO             198
KOTA BENGKULU                   196
KOTA TERNATE                    195
KABUPATEN MINAHASA              194
KOTA DENPASAR                   185
KOTA JAKARTA BARAT              157
KOTA BATAM                      156
KABUPATEN BANTUL                156
KOTA SERANG                     151
KOTA YOGYAKARTA                 150
KABUPATEN POLEWALI MANDAR       150
KABUPATEN BANJAR                150
KABUPATEN KOTAWARINGIN TIMUR    148
KABUPATEN KAPUAS                147
KOTA BANDUNG                    146
KOTA TANJUNG PINANG             145
KOTA PALANGKA RAYA              144
KOTA BANJAR BARU                144
KOTA BANJARMASIN                144
KOTA BUKIT TINGGI               144
KOTA JAKARTA SELATAN            142
KOTA BALIKPAPAN                 142
KABUPATEN BINTAN                142
KOTA BOGOR                      141
KOTA CILEGON                    140
KOTA SAMARINDA                  139
KOTA MALANG                     139
KOTA PADANG                     139
KABUPATEN LAMPUNG SELATAN       137
KOTA SURABAYA                   137
KABUPATEN SIDOARJO              137
KABUPATEN MAJENE                135
KOTA BANDAR LAMPUNG             134
KOTA JAKARTA TIMUR              131
KABUPATEN MAMUJU                130
KABUPATEN TANGERANG             130
KABUPATEN KUTAI KARTANEGARA     129
KABUPATEN BOGOR                 128
KABUPATEN PADANG PARIAMAN       128
KABUPATEN SLEMAN                120
KOTA METRO                      117
Name: count, dtype: int64
-----------------------------------


Kolom kecamatan memiliki 219 kategori unik.
kecamatan
Kecamatan JAMBI 3            309
Kecamatan JAMBI 1            294
Kecamatan JAMBI 2            260
Kecamatan GORONTALO 2        177
Kecamatan GORONTALO 1        161
Kecamatan SURAKARTA 1        151
Kecamatan SURAKARTA 2        147
Kecamatan SEMARANG 1         145
Kecamatan KUPANG 2           141
Kecamatan SEMARANG 2         139
Kecamatan PALEMBANG 2        128
Kecamatan KUPANG 1           125
Kecamatan KUPANG 3           124
Kecamatan PEKANBARU 2        124
Kecamatan SERDANG 2          123
Kecamatan BARAT 1            122
Kecamatan TIMUR 2            122
Kecamatan BANGKA 2           122
Kecamatan BADUNG 2           121
Kecamatan JAYAPURA 1         120
Kecamatan BARAT 3            118
Kecamatan TIMUR 1            118
Kecamatan TENGAH 2           118
Kecamatan ACEH 2             117
Kecamatan BOGOR 2            117
Kecamatan POSO 1             116
Kecamatan SERDANG 1          115
Kecamatan BANGKA 1           115
Kecamatan MAKASSAR 2         114
Kecamatan BOGOR 1            112
Kecamatan BULUNGAN 2         111
Kecamatan TENGAH 1           110
Kecamatan JAYAPURA 3         110
Kecamatan KONAWE 2           110
Kecamatan BULUNGAN 1         109
Kecamatan SORONG 2           109
Kecamatan BADUNG 1           109
Kecamatan SORONG 1           108
Kecamatan JAYAPURA 4         108
Kecamatan BESAR 1            107
Kecamatan MAKASSAR 1         106
Kecamatan SELATAN 2          105
Kecamatan ACEH 1             105
Kecamatan TARAKAN 2          104
Kecamatan TARAKAN 1          103
Kecamatan BESAR 2            103
Kecamatan MANOKWARI 2        103
Kecamatan BARAT 2            103
Kecamatan SELATAN 1          101
Kecamatan KONAWE 1           100
Kecamatan BENGKULU 2         100
Kecamatan JAYAPURA 2         100
Kecamatan PEKANBARU 1         98
Kecamatan MANOKWARI 1         98
Kecamatan BENGKULU 1          96
Kecamatan PALEMBANG 1         93
Kecamatan POSO 2              93
Kecamatan KAMPAR 2            93
Kecamatan LEBONG 3            87
Kecamatan KAMPAR 3            85
Kecamatan BATAM 1             83
Kecamatan MINAHASA 2          80
Kecamatan LEBONG 2            80
Kecamatan PALU 1              80
Kecamatan BANYUMAS 4          80
Kecamatan RAYA 1              79
Kecamatan KAMPAR 1            78
Kecamatan YOGYAKARTA 1        78
Kecamatan MAROS 3             77
Kecamatan BANJARBARU 1        76
Kecamatan PONTIANAK 1         75
Kecamatan CILEGON 1           75
Kecamatan TANJUNGPINANG 2     75
Kecamatan LEBONG 1            74
Kecamatan PALANGKARAYA 2      74
Kecamatan ENIM 1              74
Kecamatan BATAM 2             73
Kecamatan AMBON 1             73
Kecamatan TERNATE 1           72
Kecamatan YOGYAKARTA 2        72
Kecamatan MATARAM 1           72
Kecamatan RAYA 3              71
Kecamatan PALANGKARAYA 1      70
Kecamatan TANJUNGPINANG 1     70
Kecamatan BANYUMAS 3          70
Kecamatan ENIM 2              69
Kecamatan MEDAN 1             69
Kecamatan PONTIANAK 3         69
Kecamatan RAYA 2              68
Kecamatan BANJARBARU 2        68
Kecamatan PALU 3              67
Kecamatan AMBON 3             66
Kecamatan MANADO 4            66
Kecamatan CILEGON 2           65
Kecamatan SLEMAN 2            65
Kecamatan MATARAM 3           65
Kecamatan PANGKALPINANG 4     64
Kecamatan AMBON 2             64
Kecamatan TERNATE 3           64
Kecamatan PONTIANAK 2         63
Kecamatan GORONTALO 3         63
Kecamatan BANYUMAS 2          63
Kecamatan PANGKALPINANG 1     63
Kecamatan ENIM 3              63
Kecamatan MATARAM 2           63
Kecamatan MAROS 1             62
Kecamatan PALU 2              61
Kecamatan MAROS 4             60
Kecamatan TERNATE 2           59
Kecamatan MINAHASA 1          59
Kecamatan KENDARI 1           58
Kecamatan KUPANG 4            57
Kecamatan BANYUMAS 1          57
Kecamatan KENDARI 2           57
Kecamatan MEDAN 4             56
Kecamatan UTARA 1             55
Kecamatan SLEMAN 1            55
Kecamatan MINAHASA 3          55
Kecamatan MEDAN 2             54
Kecamatan KARTANEGARA 2       54
Kecamatan UTARA 2             54
Kecamatan BUKITTINGGI 3       54
Kecamatan BUKITTINGGI 2       54
Kecamatan BANJARMASIN 3       53
Kecamatan DENPASAR 3          52
Kecamatan PADANG 1            51
Kecamatan MANADO 3            51
Kecamatan BANJARMASIN 1       51
Kecamatan PADANG 2            50
Kecamatan PANGKALPINANG 3     49
Kecamatan UTARA 4             49
Kecamatan MAMUJU 1            49
Kecamatan UTARA 3             49
Kecamatan BANTUL 4            48
Kecamatan MANADO 1            48
Kecamatan BANTUL 1            48
Kecamatan MAMUJU 2            47
Kecamatan DENPASAR 1          46
Kecamatan BANDUNG 2           46
Kecamatan DENPASAR 4          46
Kecamatan TANGERANG 2         45
Kecamatan LAMPUNG 3           45
Kecamatan KENDARI 4           45
Kecamatan MAROS 2             45
Kecamatan LAMPUNG 1           45
Kecamatan METRO 3             45
Kecamatan PARIAMAN 2          45
Kecamatan MANDAR 3            45
Kecamatan PANGKALPINANG 2     45
Kecamatan LAMPUNG 2           44
Kecamatan KENDARI 3           44
Kecamatan TANGERANG 1         43
Kecamatan MEDAN 3             43
Kecamatan SERANG 3            43
Kecamatan BARAT 4             42
Kecamatan SERANG 4            42
Kecamatan PARIAMAN 1          42
Kecamatan BALIKPAPAN 3        42
Kecamatan BANJAR 1            42
Kecamatan TANGERANG 3         42
Kecamatan SELATAN 4           41
Kecamatan MANADO 2            41
Kecamatan MANDAR 1            41
Kecamatan KAPUAS 2            41
Kecamatan DENPASAR 2          41
Kecamatan PARIAMAN 3          41
Kecamatan SURABAYA 4          40
Kecamatan BANJARMASIN 2       40
Kecamatan BOGOR 3             40
Kecamatan BANJAR 2            39
Kecamatan METRO 1             39
Kecamatan KARTANEGARA 1       39
Kecamatan MAJENE 1            39
Kecamatan BINTAN 2            39
Kecamatan BALIKPAPAN 1        39
Kecamatan TIMUR 3             39
Kecamatan PADANG 3            38
Kecamatan SIDOARJO 3          38
Kecamatan SAMARINDA 2         38
Kecamatan KAPUAS 4            38
Kecamatan MALANG 2            38
Kecamatan SAMARINDA 1         38
Kecamatan SURABAYA 2          38
Kecamatan BANDUNG 1           38
Kecamatan MAJENE 4            37
Kecamatan MANDAR 4            36
Kecamatan BANJAR 4            36
Kecamatan BUKITTINGGI 1       36
Kecamatan SIDOARJO 1          36
Kecamatan BANDUNG 4           36
Kecamatan BINTAN 4            36
Kecamatan KARTANEGARA 3       36
Kecamatan BINTAN 1            36
Kecamatan BANTUL 3            35
Kecamatan MALANG 3            35
Kecamatan KAPUAS 1            35
Kecamatan BALIKPAPAN 2        35
Kecamatan MALANG 1            34
Kecamatan SERANG 2            34
Kecamatan MAMUJU 3            34
Kecamatan SAMARINDA 3         34
Kecamatan BANJAR 3            33
Kecamatan KAPUAS 3            33
Kecamatan MAJENE 2            33
Kecamatan SIDOARJO 2          33
Kecamatan METRO 2             33
Kecamatan SELATAN 3           32
Kecamatan SERANG 1            32
Kecamatan MALANG 4            32
Kecamatan BINTAN 3            31
Kecamatan SURABAYA 1          30
Kecamatan SIDOARJO 4          30
Kecamatan SURABAYA 3          29
Kecamatan SAMARINDA 4         29
Kecamatan MANDAR 2            28
Kecamatan BALIKPAPAN 4        26
Kecamatan MAJENE 3            26
Kecamatan BANDUNG 3           26
Kecamatan BANTUL 2            25
Name: count, dtype: int64
-----------------------------------


Kolom kode_toko memiliki 405 kategori unik.
kode_toko
TK-KOT-263    152
TK-KOT-441    145
TK-KOT-445    145
TK-KOT-321    121
TK-KAB-371    118
TK-KOT-224     95
TK-KAB-608     87
TK-KAB-538     87
TK-KAB-936     86
TK-KAB-229     86
TK-KOT-394     82
TK-KAB-753     82
TK-KAB-467     82
TK-KAB-484     80
TK-KOT-449     80
TK-KOT-921     80
TK-KAB-939     79
TK-KOT-831     77
TK-KOT-477     77
TK-KAB-350     77
TK-KOT-239     76
TK-KOT-204     72
TK-KAB-931     72
TK-KAB-618     72
TK-KOT-373     70
TK-KOT-212     70
TK-KAB-882     70
TK-KOT-503     69
TK-KAB-801     69
TK-KAB-750     68
TK-KOT-663     68
TK-KOT-683     67
TK-KOT-994     67
TK-KOT-650     67
TK-KAB-754     66
TK-KOT-418     65
TK-KAB-347     65
TK-KOT-881     65
TK-KOT-259     64
TK-KOT-957     64
TK-KOT-772     64
TK-KAB-477     62
TK-KOT-355     62
TK-KAB-961     61
TK-KAB-530     61
TK-KOT-675     61
TK-KOT-574     61
TK-KOT-811     60
TK-KAB-605     60
TK-KAB-667     60
TK-KOT-928     60
TK-KAB-317     60
TK-KOT-889     59
TK-KAB-368     59
TK-KAB-442     58
TK-KOT-781     58
TK-KOT-986     58
TK-KAB-700     57
TK-KOT-327     57
TK-KOT-622     57
TK-KAB-807     57
TK-KAB-643     56
TK-KAB-941     56
TK-KOT-363     56
TK-KOT-131     55
TK-KAB-587     55
TK-KAB-290     55
TK-KAB-334     55
TK-KAB-175     54
TK-KAB-215     54
TK-KAB-299     54
TK-KAB-837     53
TK-KAB-721     53
TK-KOT-958     53
TK-KAB-571     53
TK-KAB-686     53
TK-KOT-451     52
TK-KAB-144     52
TK-KAB-308     51
TK-KOT-495     51
TK-KOT-637     51
TK-KOT-114     51
TK-KOT-922     51
TK-KAB-116     51
TK-KOT-769     50
TK-KOT-555     50
TK-KAB-637     50
TK-KOT-904     50
TK-KOT-890     50
TK-KOT-488     50
TK-KOT-975     50
TK-KOT-532     49
TK-KOT-274     49
TK-KOT-272     49
TK-KOT-229     49
TK-KOT-245     49
TK-KOT-694     48
TK-KOT-822     48
TK-KOT-240     47
TK-KOT-432     47
TK-KAB-526     47
TK-KOT-148     47
TK-KAB-147     47
TK-KOT-829     46
TK-KAB-329     46
TK-KOT-415     46
TK-KOT-940     46
TK-KOT-278     46
TK-KAB-787     45
TK-KAB-727     45
TK-KAB-656     45
TK-KAB-613     45
TK-KOT-194     45
TK-KOT-944     44
TK-KOT-744     44
TK-KAB-211     43
TK-KAB-919     43
TK-KOT-189     43
TK-KOT-724     43
TK-KAB-567     43
TK-KOT-559     43
TK-KAB-452     43
TK-KOT-372     43
TK-KOT-849     43
TK-KAB-192     43
TK-KAB-164     42
TK-KAB-785     42
TK-KOT-732     42
TK-KOT-181     42
TK-KAB-678     42
TK-KOT-973     42
TK-KAB-370     42
TK-KAB-544     42
TK-KOT-337     42
TK-KOT-991     41
TK-KOT-847     41
TK-KAB-986     41
TK-KOT-164     41
TK-KOT-828     41
TK-KAB-572     41
TK-KOT-892     41
TK-KAB-453     41
TK-KAB-535     41
TK-KOT-826     41
TK-KOT-638     41
TK-KOT-203     41
TK-KOT-987     40
TK-KOT-872     40
TK-KAB-292     40
TK-KOT-939     40
TK-KAB-182     40
TK-KOT-126     40
TK-KAB-640     40
TK-KOT-429     40
TK-KOT-984     39
TK-KAB-345     39
TK-KAB-449     39
TK-KOT-633     39
TK-KAB-956     39
TK-KOT-612     39
TK-KOT-967     38
TK-KAB-903     38
TK-KOT-539     38
TK-KOT-999     38
TK-KAB-698     38
TK-KAB-673     38
TK-KAB-458     38
TK-KOT-285     38
TK-KAB-429     37
TK-KAB-647     37
TK-KOT-496     37
TK-KAB-540     37
TK-KOT-861     37
TK-KOT-678     37
TK-KOT-770     37
TK-KOT-333     37
TK-KAB-912     37
TK-KOT-469     37
TK-KOT-618     37
TK-KAB-958     37
TK-KAB-670     36
TK-KOT-909     36
TK-KAB-161     36
TK-KOT-836     36
TK-KAB-806     36
TK-KAB-403     36
TK-KOT-140     36
TK-KOT-101     36
TK-KOT-851     35
TK-KOT-857     35
TK-KOT-627     35
TK-KOT-522     35
TK-KOT-187     35
TK-KAB-937     35
TK-KOT-303     35
TK-KOT-658     35
TK-KAB-777     35
TK-KAB-524     35
TK-KOT-133     35
TK-KOT-791     35
TK-KOT-846     34
TK-KAB-885     34
TK-KAB-590     34
TK-KOT-207     34
TK-KAB-887     34
TK-KOT-423     34
TK-KOT-529     34
TK-KOT-298     34
TK-KAB-226     34
TK-KOT-130     34
TK-KAB-723     33
TK-KOT-896     33
TK-KAB-717     33
TK-KOT-158     33
TK-KAB-894     33
TK-KOT-233     33
TK-KAB-205     33
TK-KOT-876     33
TK-KAB-997     33
TK-KAB-741     32
TK-KAB-479     32
TK-KAB-883     32
TK-KAB-525     32
TK-KAB-625     32
TK-KAB-149     32
TK-KOT-243     32
TK-KOT-734     32
TK-KOT-340     31
TK-KOT-244     31
TK-KAB-762     31
TK-KAB-480     31
TK-KAB-730     31
TK-KAB-668     31
TK-KOT-326     31
TK-KAB-496     31
TK-KAB-112     31
TK-KOT-310     30
TK-KOT-631     30
TK-KOT-486     30
TK-KOT-352     30
TK-KAB-771     30
TK-KAB-790     30
TK-KOT-779     30
TK-KAB-622     30
TK-KAB-473     30
TK-KAB-796     29
TK-KAB-779     29
TK-KAB-141     29
TK-KOT-175     29
TK-KAB-451     29
TK-KAB-770     29
TK-KOT-976     29
TK-KAB-489     29
TK-KAB-470     28
TK-KAB-255     28
TK-KOT-813     28
TK-KOT-830     27
TK-KOT-470     27
TK-KOT-953     27
TK-KAB-381     27

#### Table Survey

In [34]:
check_categorical_value(table_survey)

Kolom no_survey memiliki 8338 kategori unik.
no_survey
SRV-20260911-5238    2
SRV-20260621-5679    2
SRV-20261008-5292    2
SRV-20260907-3495    2
SRV-20260128-1918    2
SRV-20260727-2230    2
SRV-20261003-7175    2
SRV-20260204-5494    2
SRV-20260201-8473    2
SRV-20260912-5490    2
SRV-20260307-8061    2
SRV-20261106-7416    2
SRV-20260831-8540    1
SRV-20260831-3152    1
SRV-20260831-4361    1
SRV-20260831-6990    1
SRV-20260831-7014    1
SRV-20260831-1146    1
SRV-20260831-3981    1
SRV-20260831-6125    1
SRV-20260831-6513    1
SRV-20260831-8677    1
SRV-20260831-7913    1
SRV-20260831-1153    1
SRV-20260831-5281    1
SRV-20260831-5387    1
SRV-20260831-5401    1
SRV-20260831-8907    1
SRV-20260830-7585    1
SRV-20260830-4706    1
SRV-20260830-2612    1
SRV-20260830-5213    1
SRV-20260830-8966    1
SRV-20260830-6769    1
SRV-20260830-5182    1
SRV-20260830-1422    1
SRV-20260831-6426    1
SRV-20260101-9741    1
SRV-20260831-7307    1
SRV-20260901-5857    1
SRV-20260902-6534    1
SRV-20260901-8711    1
SRV-20260901-8664    1
SRV-20260901-5460    1
SRV-20260901-7072    1
SRV-20260901-9298    1
SRV-20260901-7587    1
SRV-20260901-9372    1
SRV-20260901-8059    1
SRV-20260901-9568    1
SRV-20260901-4551    1
SRV-20260901-1771    1
SRV-20260901-4691    1
SRV-20260901-9956    1
SRV-20260901-6413    1
SRV-20260831-5187    1
SRV-20260901-7543    1
SRV-20260901-7769    1
SRV-20260901-2687    1
SRV-20260901-1168    1
SRV-20260901-8335    1
SRV-20260901-2459    1
SRV-20260901-7764    1
SRV-20260901-8254    1
SRV-20260901-9962    1
SRV-20260831-8637    1
SRV-20260831-3305    1
SRV-20260831-4132    1
SRV-20260831-1051    1
SRV-20260830-5090    1
SRV-20260831-8804    1
SRV-20260830-2317    1
SRV-20260830-1273    1
SRV-20260902-8505    1
SRV-20260828-9089    1
SRV-20260828-6422    1
SRV-20260828-8984    1
SRV-20260828-9076    1
SRV-20260828-9020    1
SRV-20260828-9641    1
SRV-20260828-3252    1
SRV-20260828-9842    1
SRV-20260828-1407    1
SRV-20260828-1840    1
SRV-20260828-8420    1
SRV-20260828-8949    1
SRV-20260828-8795    1
SRV-20260828-6941    1
SRV-20260828-7603    1
SRV-20260827-2763    1
SRV-20260827-7560    1
SRV-20260827-6763    1
SRV-20260827-4704    1
SRV-20260827-1043    1
SRV-20260827-3399    1
SRV-20260827-1907    1
SRV-20260827-8778    1
SRV-20260827-4375    1
SRV-20260827-8974    1
SRV-20260827-9910    1
SRV-20260827-8332    1
SRV-20260827-5965    1
SRV-20260827-8869    1
SRV-20260828-8804    1
SRV-20260828-1677    1
SRV-20260828-3845    1
SRV-20260829-3612    1
SRV-20260830-3318    1
SRV-20260830-3170    1
SRV-20260830-9361    1
SRV-20260830-1879    1
SRV-20260830-2626    1
SRV-20260830-4806    1
SRV-20260830-9646    1
SRV-20260830-7275    1
SRV-20260830-1405    1
SRV-20260830-1403    1
SRV-20260829-5363    1
SRV-20260829-8277    1
SRV-20260829-2220    1
SRV-20260829-7031    1
SRV-20260828-2112    1
SRV-20260829-4012    1
SRV-20260829-7354    1
SRV-20260829-7424    1
SRV-20260829-3627    1
SRV-20260829-9968    1
SRV-20260829-5114    1
SRV-20260829-1697    1
SRV-20260829-5811    1
SRV-20260829-4087    1
SRV-20260829-7886    1
SRV-20260829-6720    1
SRV-20260829-3136    1
SRV-20260829-3856    1
SRV-20260902-3347    1
SRV-20260902-6064    1
SRV-20260902-7616    1
SRV-20260902-3289    1
SRV-20260906-9757    1
SRV-20260906-2039    1
SRV-20260906-4833    1
SRV-20260906-2654    1
SRV-20260906-5125    1
SRV-20260906-3903    1
SRV-20260906-4976    1
SRV-20260906-9623    1
SRV-20260906-9525    1
SRV-20260905-1832    1
SRV-20260905-2761    1
SRV-20260905-6228    1
SRV-20260905-2706    1
SRV-20260905-7757    1
SRV-20260905-7717    1
SRV-20260905-2356    1
SRV-20260905-6584    1
SRV-20260905-4178    1
SRV-20260905-4057    1
SRV-20260905-5294    1
SRV-20260905-4215    1
SRV-20260905-1760    1
SRV-20260905-8181    1
SRV-20260905-2273    1
SRV-20260905-3546    1
SRV-20260905-6614    1
SRV-20260905-4942    1
SRV-20260905-7949    1
SRV-20260905-4121    1
SRV-20260906-1569    1
SRV-20260906-6126    1
SRV-20260906-8494    1
SRV-20260907-5318    1
SRV-20260908-3630    1
SRV-20260908-8739    1
SRV-20260908-9582    1
SRV-20260908-8228    1
SRV-20260907-2531    1
SRV-20260907-5573    1
SRV-20260907-2066    1
SRV-20260907-4944    1
SRV-20260907-6136    1
SRV-20260907-6593    1
SRV-20260907-6952    1
SRV-20260907-2420    1
SRV-20260907-4424    1
SRV-20260907-4305    1
SRV-20260906-6342    1
SRV-20260907-2656    1
SRV-20260907-4693    1
SRV-20260907-6385    1
SRV-20260907-6779    1
SRV-20260907-3733    1
SRV-20260907-7721    1
SRV-20260907-6489    1
SRV-20260906-1920    1
SRV-20260906-5229    1
SRV-20260906-6842    1
SRV-20260906-5065    1
SRV-20260906-5491    1
SRV-20260906-4363    1
SRV-20260905-6199    1
SRV-20260904-7385    1
SRV-20260904-1923    1
SRV-20260902-2089    1
SRV-20260903-2506    1
SRV-20260903-7565    1
SRV-20260903-9378    1
SRV-20260903-7800    1
SRV-20260903-9414    1
SRV-20260903-8844    1
SRV-20260903-9379    1
SRV-20260903-5257    1
SRV-20260903-3698    1
SRV-20260903-2387    1
SRV-20260903-1213    1
SRV-20260903-5171    1
SRV-20260903-8642    1
SRV-20260902-5828    1
SRV-20260903-7507    1
SRV-20260902-6015    1
SRV-20260902-9255    1
SRV-20260902-3822    1
SRV-20260902-4968    1
SRV-20260902-7707    1
SRV-20260902-7555    1
SRV-20260902-4005    1
SRV-20260902-9010    1
SRV-20260902-4322    1
SRV-20260902-2049    1
SRV-20260902-9307    1
SRV-20260827-9189    1
SRV-20260902-3069    1
SRV-20260903-7945    1
SRV-20260903-4289    1
SRV-20260904-5123    1
SRV-20260904-6825    1
SRV-20260904-6170    1
SRV-20260904-2506    1
SRV-20260904-2062    1
SRV-20260904-3798    1
SRV-20260904-6237    1
SRV-20260904-9887    1
SRV-20260904-6749    1
SRV-20260904-6381    1
SRV-20260904-8160    1
SRV-20260904-9515    1
SRV-20260904-4418    1
SRV-20260904-4619    1
SRV-20260904-5191    1
SRV-20260904-3183    1
SRV-20260903-7012    1
SRV-20260904-7884    1
SRV-20260904-6690    1
SRV-20260904-8840    1
SRV-20260904-5936    1
SRV-20260904-7014    1
SRV-20260904-4647    1
SRV-20260904-4069    1
SRV-20260904-7162    1
SRV-20260904-1344    1
SRV-20260903-5540    1
SRV-20260903-7344    1
SRV-20260903-5889    1
SRV-20260903-2636    1
SRV-20260827-5250    1
SRV-20260827-6449    1
SRV-20260827-8022    1
SRV-20260820-4512    1
SRV-20260820-7402    1
SRV-20260820-1038    1
SRV-20260820-8537    1
SRV-20260820-9745    1
SRV-20260820-3344    1
SRV-20260819-2587    1
SRV-20260819-8722    1
SRV-20260819-6195    1
SRV-20260819-1864    1
SRV-20260819-8034    1
SRV-20260819-4428    1
SRV-20260819-9255    1
SRV-20260819-2361    1
SRV-20260819-5562    1
SRV-20260819-1790    1
SRV-20260819-7857    1
SRV-20260819-4842    1
SRV-20260819-4031    1
SRV-20260819-5308    1
SRV-20260819-5572    1
SRV-20260819-8376    1
SRV-20260819-8903    1
SRV-20260819-6856    1
SRV-20260819-5099    1
SRV-20260818-2658    1
SRV-20260818-2238    1
SRV-20260818-7654    1
SRV-20260818-7954    1
SRV-20260818-7331    1
SRV-20260820-9203    1
SRV-20260820-8002    1
SRV-20260827-7807    1
SRV-20260820-4250    1
SRV-20260821-3474    1
SRV-20260821-7589    1
SRV-20260821-4850    1
SRV-20260821-2758    1
SRV-20260821-6408    1
SRV-20260821-3051    1
SRV-20260821-4849    1
SRV-20260821-3436    1
SRV-20260821-8749    1
SRV-20260821-2982    1
SRV-20260821-7858    1
SRV-20260821-2534    1
SRV-20260820-1767    1
SRV-20260820-5348    1
SRV-20260820-1158    1
SRV-20260820-7791    1
SRV-20260820-4932    1
SRV-20260820-5375    1
SRV-20260820-9596    1
SRV-20260820-9005    1
SRV-20260820-6650    1
SRV-20260820-1579    1
SRV-20260820-2045    1
SRV-20260820-8966    1
SRV-20260820-6777    1
SRV-20260820-6803    1
SRV-20260820-6667    1
SRV-20260820-4732    1
SRV-20260820-8660    1
SRV-20260818-6151    1
SRV-20260818-8199    1
SRV-20260818-7855    1
SRV-20260818-4749    1
SRV-20260817-3430    1
SRV-20260817-4267    1
SRV-20260817-7503    1
SRV-20260816-9512    1
SRV-20260816-2207    1
SRV-20260816-6275    1
SRV-20260816-5771    1
SRV-20260816-7124    1
SRV-20260816-8812    1
SRV-20260816-4718    1
SRV-20260816-7754    1
SRV-20260816-8550    1
SRV-20260816-5775    1
SRV-20260816-6242    1
SRV-20260816-9583    1
SRV-20260816-7886    1
SRV-20260816-4563    1
SRV-20260816-8696    1
SRV-20260816-7408    1
SRV-20260816-1946    1
SRV-20260816-1318    1
SRV-20260816-2524    1
SRV-20260816-7863    1
SRV-20260816-2048    1
SRV-20260816-7676    1
SRV-20260816-7338    1
SRV-20260816-5872    1
SRV-20260816-1537    1
SRV-20260816-3417    1
SRV-20260817-4604    1
SRV-20260817-2678    1
SRV-20260817-7453    1
SRV-20260818-9514    1
SRV-20260818-1430    1
SRV-20260818-7113    1
SRV-20260818-1767    1
SRV-20260818-1436    1
SRV-20260818-4369    1
SRV-20260818-7576    1
SRV-20260818-9518    1
SRV-20260818-2500    1
SRV-20260818-5372    1
SRV-20260818-6408    1
SRV-20260818-8007    1
SRV-20260818-6868    1
SRV-20260818-1034    1
SRV-20260818-9607    1
SRV-20260817-3905    1
SRV-20260817-3144    1
SRV-20260817-7607    1
SRV-20260817-1503    1
SRV-20260817-3651    1
SRV-20260817-8521    1
SRV-20260817-8996    1
SRV-20260817-2782    1
SRV-20260817-1089    1
SRV-20260817-9007    1
SRV-20260817-5403    1
SRV-20260817-8704    1
SRV-20260817-1611    1
SRV-20260817-3438    1
SRV-20260821-7501    1
SRV-20260821-1298    1
SRV-20260821-8890    1
SRV-20260824-9619    1
SRV-20260825-6273    1
SRV-20260825-6586    1
SRV-20260825-4463    1
SRV-20260825-8140    1
SRV-20260825-4478    1
SRV-20260825-9900    1
SRV-20260825-5143    1
SRV-20260825-4546    1
SRV-20260825-6438    1
SRV-20260825-5445    1
SRV-20260825-7700    1
SRV-20260825-3661    1
SRV-20260825-5225    1
SRV-20260825-8838    1
SRV-20260825-5359    1
SRV-20260824-1042    1
SRV-20260824-7169    1
SRV-20260824-8712    1
SRV-20260824-2056    1
SRV-20260824-7987    1
SRV-20260824-4352    1
SRV-20260824-7165    1
SRV-20260824-4232    1
SRV-20260824-6759    1
SRV-20260824-3583    1
SRV-20260824-2462    1
SRV-20260824-5379    1
SRV-20260824-1770    1
SRV-20260824-1525    1
SRV-20260825-5504    1
SRV-20260825-3256    1
SRV-20260825-9635    1
SRV-20260826-8067    1
SRV-20260908-3787    1
SRV-20260827-6350    1
SRV-20260826-3543    1
SRV-20260826-6807    1
SRV-20260826-2309    1
SRV-20260826-1031    1
SRV-20260826-5552    1
SRV-20260826-5070    1
SRV-20260826-9973    1
SRV-20260826-7600    1
SRV-20260826-3190    1
SRV-20260826-5659    1
SRV-20260826-5812    1
SRV-20260826-4520    1
SRV-20260825-3900    1
SRV-20260826-9968    1
SRV-20260826-1269    1
SRV-20260826-3635    1
SRV-20260826-2109    1
SRV-20260826-4343    1
SRV-20260826-4685    1
SRV-20260826-7177    1
SRV-20260826-7881    1
SRV-20260826-6742    1
SRV-20260826-5155    1
SRV-20260826-8264    1
SRV-20260826-7970    1
SRV-20260826-8668    1
SRV-20260824-5314    1
SRV-20260824-8706    1
SRV-20260821-5319    1
SRV-20260824-7920    1
SRV-20260822-1145    1
SRV-20260822-3268    1
SRV-20260822-9754    1
SRV-20260822-5403    1
SRV-20260822-5958    1
SRV-20260822-7868    1
SRV-20260822-6638    1
SRV-20260822-5825    1
SRV-20260822-1341    1
SRV-20260822-4855    1
SRV-20260822-3965    1
SRV-20260822-6670    1
SRV-20260822-5224    1
SRV-20260822-2617    1
SRV-20260822-7307    1
SRV-20260822-2637    1
SRV-20260822-7275    1
SRV-20260822-8396    1
SRV-20260822-8248    1
SRV-20260822-2929    1
SRV-20260822-3449    1
SRV-20260821-5878    1
SRV-20260821-4987    1
SRV-20260821-8296    1
SRV-20260821-8791    1
SRV-20260821-6556    1
SRV-20260821-7367    1
SRV-20260821-6789    1
SRV-20260821-6826    1
SRV-20260822-7553    1
SRV-20260822-5180    1
SRV-20260822-6854    1
SRV-20260823-5784    1
SRV-20260824-2186    1
SRV-20260824-6683    1
SRV-20260824-9665    1
SRV-20260824-7531    1
SRV-20260824-2252    1
SRV-20260824-4044    1
SRV-20260824-1646    1
SRV-20260823-8454    1
SRV-20260823-9032    1
SRV-20260823-1520    1
SRV-20260823-9181    1
SRV-20260823-1217    1
SRV-20260823-9412    1
SRV-20260823-7227    1
SRV-20260822-8789    1
SRV-20260823-4256    1
SRV-20260823-1673    1
SRV-20260823-6995    1
SRV-20260823-8556    1
SRV-20260823-3391    1
SRV-20260823-9755    1
SRV-20260823-1295    1
SRV-20260823-8212    1
SRV-20260823-2999    1
SRV-20260823-9736    1
SRV-20260823-8678    1
SRV-20260822-4879    1
SRV-20260822-7636    1
SRV-20260908-4915    1
SRV-20260908-5045    1
SRV-20260908-8780    1
SRV-20260923-4797    1
SRV-20260923-3522    1
SRV-20260923-3019    1
SRV-20260923-3536    1
SRV-20260923-8540    1
SRV-20260923-9805    1
SRV-20260923-2398    1
SRV-20260923-7522    1
SRV-20260923-3940    1
SRV-20260923-3127    1
SRV-20260923-8791    1
SRV-20260923-2410    1
SRV-20260922-1194    1
SRV-20260922-3827    1
SRV-20260922-2558    1
SRV-20260922-5628    1
SRV-20260922-6982    1
SRV-20260922-2812    1
SRV-20260922-7513    1
SRV-20260922-3476    1
SRV-20260922-7196    1
SRV-20260922-3307    1
SRV-20260922-3741    1
SRV-20260922-2109    1
SRV-20260922-1006    1
SRV-20260922-2619    1
SRV-20260922-6399    1
SRV-20260922-9486    1
SRV-20260922-6811    1
SRV-20260922-3379    1
SRV-20260923-5000    1
SRV-20260923-4218    1
SRV-20260908-3026    1
SRV-20260923-9524    1
SRV-20260924-4325    1
SRV-20260924-8351    1
SRV-20260924-5614    1
SRV-20260924-8123    1
SRV-20260924-8866    1
SRV-20260924-1431    1
SRV-20260924-1202    1
SRV-20260924-3831    1
SRV-20260924-6673    1
SRV-20260924-5089    1
SRV-20260924-2751    1
SRV-20260924-4680    1
SRV-20260924-5947    1
SRV-20260924-1608    1
SRV-20260924-8477    1
SRV-20260924-2467    1
SRV-20260924-1054    1
SRV-20260924-3815    1
SRV-20260923-9045    1
SRV-20260923-3918    1
SRV-20260923-3734    1
SRV-20260923-5129    1
SRV-20260923-7418    1
SRV-20260923-6579    1
SRV-20260923-3598    1
SRV-20260923-5657    1
SRV-20260923-6841    1
SRV-20260923-7012    1
SRV-20260923-2947    1
SRV-20260922-1884    1
SRV-20260922-2784    1
SRV-20260922-5081    1
SRV-20260922-1070    1
SRV-20260920-3243    1
SRV-20260920-1611    1
SRV-20260920-6894    1
SRV-20260920-4083    1
SRV-20260920-2756    1
SRV-20260920-4294    1
SRV-20260920-8762    1
SRV-20260920-9626    1
SRV-20260920-8487    1
SRV-20260920-3955    1
SRV-20260920-1560    1
SRV-20260920-7450    1
SRV-20260920-4213    1
SRV-20260919-9183    1
SRV-20260919-4618    1
SRV-20260919-8556    1
SRV-20260919-1031    1
SRV-20260919-4559    1
SRV-20260919-3048    1
SRV-20260919-5854    1
SRV-20260919-8042    1
SRV-20260919-3806    1
SRV-20260919-8967    1
SRV-20260919-1259    1
SRV-20260919-8485    1
SRV-20260919-4241    1
SRV-20260919-9275    1
SRV-20260919-3164    1
SRV-20260919-4813    1
SRV-20260920-3479    1
SRV-20260920-1158    1
SRV-20260920-5565    1
SRV-20260921-8406    1
SRV-20260922-1561    1
SRV-20260922-8728    1
SRV-20260922-8679    1
SRV-20260922-6638    1
SRV-20260922-8667    1
SRV-20260922-7453    1
SRV-20260922-8015    1
SRV-20260921-5920    1
SRV-20260921-1038    1
SRV-20260921-4652    1
SRV-20260921-5521    1
SRV-20260921-4238    1
SRV-20260921-9047    1
SRV-20260921-8515    1
SRV-20260920-7533    1
SRV-20260921-1735    1
SRV-20260921-8196    1
SRV-20260921-4162    1
SRV-20260921-1491    1
SRV-20260921-7936    1
SRV-20260921-8940    1
SRV-20260921-8461    1
SRV-20260921-3450    1
SRV-20260921-5650    1
SRV-20260921-2562    1
SRV-20260920-9417    1
SRV-20260920-9644    1
SRV-20260920-1553    1
SRV-20260924-6827    1
SRV-20260924-6018    1
SRV-20260924-6166    1
SRV-20260927-4844    1
SRV-20260929-7269    1
SRV-20260928-1716    1
SRV-20260928-4083    1
SRV-20260928-5187    1
SRV-20260928-4305    1
SRV-20260928-5949    1
SRV-20260928-2360    1
SRV-20260928-5675    1
SRV-20260928-9766    1
SRV-20260928-1553    1
SRV-20260928-4049    1
SRV-20260928-5549    1
SRV-20260928-2059    1
SRV-20260928-2175    1
SRV-20260928-2488    1
SRV-20260928-5787    1
SRV-20260928-8706    1
SRV-20260928-2391    1
SRV-20260928-9867    1
SRV-20260928-3118    1
SRV-20260928-3466    1
SRV-20260928-2799    1
SRV-20260928-6210    1
SRV-20260928-7097    1
SRV-20260927-5583    1
SRV-20260927-2230    1
SRV-20260927-4003    1
SRV-20260927-8728    1
SRV-20260927-7275    1
SRV-20260929-8366    1
SRV-20260929-7908    1
SRV-20260929-4445    1
SRV-20260930-1990    1
SRV-20260930-7178    1
SRV-20260930-9332    1
SRV-20260930-1736    1
SRV-20260930-3089    1
SRV-20260930-2531    1
SRV-20260930-8437    1
SRV-20260930-8417    1
SRV-20260930-7795    1
SRV-20260930-1025    1
SRV-20260930-5933    1
SRV-20260930-7979    1
SRV-20260930-8768    1
SRV-20260930-2469    1
SRV-20260930-9805    1
SRV-20260929-9684    1
SRV-20260930-6940    1
SRV-20260929-3522    1
SRV-20260929-7702    1
SRV-20260929-3270    1
SRV-20260929-8164    1
SRV-20260929-8418    1
SRV-20260929-3453    1
SRV-20260929-5545    1
SRV-20260929-8068    1
SRV-20260929-8616    1
SRV-20260929-8783    1
SRV-20260929-5400    1
SRV-20260929-2378    1
SRV-20260927-3108    1
SRV-20260927-7861    1
SRV-20260925-6538    1
SRV-20260927-9671    1
SRV-20260926-7038    1
SRV-20260926-7555    1
SRV-20260926-7279    1
SRV-20260926-5778    1
SRV-20260926-5599    1
SRV-20260926-5348    1
SRV-20260925-6001    1
SRV-20260925-7808    1
SRV-20260925-5537    1
SRV-20260925-1441    1
SRV-20260925-8012    1
SRV-20260925-1854    1
SRV-20260925-1116    1
SRV-20260925-6638    1
SRV-20260925-4611    1
SRV-20260925-9858    1
SRV-20260925-5726    1
SRV-20260925-9343    1
SRV-20260925-1642    1
SRV-20260925-5113    1
SRV-20260925-2788    1
SRV-20260925-2400    1
SRV-20260925-7139    1
SRV-20260925-8226    1
SRV-20260925-4396    1
SRV-20260925-3181    1
SRV-20260925-3803    1
SRV-20260925-9090    1
SRV-20260925-7980    1
SRV-20260926-8207    1
SRV-20260926-4796    1
SRV-20260926-5035    1
SRV-20260927-6978    1
SRV-20260927-6727    1
SRV-20260927-5111    1
SRV-20260927-7701    1
SRV-20260927-6262    1
SRV-20260927-6459    1
SRV-20260927-9630    1
SRV-20260927-7163    1
SRV-20260927-5269    1
SRV-20260927-1717    1
SRV-20260927-8603    1
SRV-20260927-9463    1
SRV-20260927-1185    1
SRV-20260927-1515    1
SRV-20260927-6916    1
SRV-20260926-9813    1
SRV-20260927-5170    1
SRV-20260927-8177    1
SRV-20260927-4664    1
SRV-20260926-8313    1
SRV-20260926-1193    1
SRV-20260926-4041    1
SRV-20260926-7811    1
SRV-20260926-3891    1
SRV-20260926-7571    1
SRV-20260926-4554    1
SRV-20260926-1893    1
SRV-20260926-9530    1
SRV-20260926-2595    1
SRV-20260919-6424    1
SRV-20260919-9852    1
SRV-20260919-4770    1
SRV-20260910-1859    1
SRV-20260912-7254    1
SRV-20260912-2682    1
SRV-20260912-3274    1
SRV-20260912-1218    1
SRV-20260911-5595    1
SRV-20260911-8367    1
SRV-20260911-8645    1
SRV-20260911-5448    1
SRV-20260911-3949    1
SRV-20260911-9502    1
SRV-20260911-2418    1
SRV-20260911-9141    1
SRV-20260911-2025    1
SRV-20260911-1019    1
SRV-20260911-7903    1
SRV-20260911-3386    1
SRV-20260911-1677    1
SRV-20260911-3055    1
SRV-20260911-5142    1
SRV-20260911-3272    1
SRV-20260911-1798    1
SRV-20260911-3172    1
SRV-20260911-4096    1
SRV-20260911-9454    1
SRV-20260911-9883    1
SRV-20260911-1160    1
SRV-20260911-7607    1
SRV-20260911-3762    1
SRV-20260911-1872    1
SRV-20260912-4860    1
SRV-20260912-4839    1
SRV-20260912-8907    1
SRV-20260912-5387    1
SRV-20260913-2764    1
SRV-20260913-4548    1
SRV-20260913-5813    1
SRV-20260913-8486    1
SRV-20260913-3994    1
SRV-20260913-5001    1
SRV-20260913-6700    1
SRV-20260913-3071    1
SRV-20260913-9002    1
SRV-20260913-5387    1
SRV-20260913-7214    1
SRV-20260913-9788    1
SRV-20260913-4625    1
SRV-20260912-1633    1
SRV-20260912-4805    1
SRV-20260912-4265    1
SRV-20260912-5860    1
SRV-20260912-7526    1
SRV-20260912-7200    1
SRV-20260912-8407    1
SRV-20260912-6104    1
SRV-20260912-8448    1
SRV-20260912-2245    1
SRV-20260912-5601    1
SRV-20260912-2846    1
SRV-20260912-8265    1
SRV-20260912-3765    1
SRV-20260912-5692    1
SRV-20260911-6920    1
SRV-20260910-9567    1
SRV-20260913-3774    1
SRV-20260910-8356    1
SRV-20260909-1906    1
SRV-20260909-9456    1
SRV-20260909-6459    1
SRV-20260909-4690    1
SRV-20260909-2176    1
SRV-20260909-2068    1
SRV-20260909-3027    1
SRV-20260909-5711    1
SRV-20260909-5539    1
SRV-20260909-8751    1
SRV-20260909-6871    1
SRV-20260908-6537    1

In [35]:
pd.reset_option('display.max_rows')

#### Hasil Temuan Kategorikal Ini

- Tidak ada kategori pada setiap kolom yang terindikasi berbeda pengetikannya meskipun maknanya sama dalam hal kemiripan (contohnya Banten & BANTEN) sehingga berpengaruh pada perhitungan jumlah kategorinya nanti
- Terdapat frasa 'Atlas' yang masih perlu diubah menjadi 'st' pada kategori di kolom product_name, distributor_name pada table survey dan kategori di kolom nama_distributor pada table CA

In [36]:
table_survey['product_name'] = table_survey['product_name'].str.replace('Atlasandar', 'Standar')
table_survey['distributor_name'] = table_survey['distributor_name'].str.replace('DiAtlasributor', 'Distributor')
table_CA['nama_distributor'] = table_CA['nama_distributor'].str.replace('DiAtlasributor', 'Distributor')

In [37]:
table_survey['product_name'].unique()

array(['Semen Fonda Standar', 'Semen Kinetiq Standar',
       'Semen BINTA Premium', 'Semen Omnicore Premium',
       'Semen Vanguard Standar', 'Semen Fonda Premium',
       'Semen Tecton Premium', 'Semen Kinetiq Premium',
       'Semen Atlas Standar', 'Semen Vanguard Premium',
       'Semen Tecton Standar', 'Semen Primebase Standar',
       'Semen TIDAR Standar', 'Semen RAJASA Premium',
       'Semen Monolith Premium', 'Semen Primebase Premium',
       'Semen RAJASA Standar', 'Semen TerraBlock Premium',
       'Semen SANJAYA Premium', 'Semen GAMA Standar',
       'Semen TIDAR Premium', 'Semen Atlas Premium',
       'Semen TerraBlock Standar', 'Semen BINTA Standar',
       'Semen Omnicore Standar', 'Semen SANJAYA Standar',
       'Semen GAMA Premium', 'Semen Monolith Standar'], dtype=object)

In [38]:
table_survey['distributor_name'].unique()

array(['PT Distributor Banten 01', 'PT Distributor Maluku Utara 02',
       'PT Distributor Papua 03', 'PT Distributor Bengkulu 02',
       'PT Distributor Bengkulu 03', 'PT Distributor Gorontalo 02',
       'PT Distributor Papua 02', 'PT Distributor Kalimantan Selatan 01',
       'PT Distributor Sulawesi Tenggara 03',
       'PT Distributor Kepulauan Bangka Belitung 03',
       'PT Distributor Jambi 01', 'PT Distributor Kepulauan Riau 01',
       'PT Distributor Aceh 01', 'PT Distributor Papua Barat 01',
       'PT Distributor Sulawesi Utara 02',
       'PT Distributor Maluku Utara 03',
       'PT Distributor Nusa Tenggara Timur 01',
       'PT Distributor Kalimantan Selatan 02', 'PT Distributor Riau 01',
       'PT Distributor Kepulauan Bangka Belitung 01',
       'PT Distributor Sulawesi Barat 01',
       'PT Distributor Sumatera Barat 02',
       'PT Distributor Di Yogyakarta 02', 'PT Distributor Jawa Tengah 03',
       'PT Distributor Dki Jakarta 03',
       'PT Distributor Sumatera Selatan 01',
       'PT Distributor Kalimantan Barat 02',
       'PT Distributor Papua Barat 02',
       'PT Distributor Kalimantan Barat 03', 'PT Distributor Jambi 03',
       'PT Distributor Lampung 03', 'PT Distributor Maluku 02',
       'PT Distributor Jawa Barat 03',
       'PT Distributor Kalimantan Utara 02', 'PT Distributor Jambi 02',
       'PT Distributor Sulawesi Tengah 02',
       'PT Distributor Kepulauan Riau 02', 'PT Distributor Riau 02',
       'PT Distributor Kalimantan Selatan 03',
       'PT Distributor Kepulauan Bangka Belitung 02',
       'PT Distributor Maluku 01', 'PT Distributor Sumatera Utara 03',
       'PT Distributor Sulawesi Selatan 01', 'PT Distributor Maluku 03',
       'PT Distributor Jawa Barat 02',
       'PT Distributor Kalimantan Timur 02',
       'PT Distributor Kalimantan Timur 03',
       'PT Distributor Gorontalo 03', 'PT Distributor Sulawesi Barat 03',
       'PT Distributor Kalimantan Tengah 02',
       'PT Distributor Kalimantan Tengah 01',
       'PT Distributor Sulawesi Barat 02', 'PT Distributor Papua 01',
       'PT Distributor Sulawesi Tenggara 01',
       'PT Distributor Nusa Tenggara Barat 03',
       'PT Distributor Di Yogyakarta 03',
       'PT Distributor Kalimantan Timur 01',
       'PT Distributor Di Yogyakarta 01', 'PT Distributor Jawa Timur 02',
       'PT Distributor Kalimantan Utara 01',
       'PT Distributor Sulawesi Utara 01', 'PT Distributor Riau 03',
       'PT Distributor Jawa Timur 01', 'PT Distributor Jawa Tengah 02',
       'PT Distributor Bali 02', 'PT Distributor Sulawesi Tengah 03',
       'PT Distributor Nusa Tenggara Barat 02',
       'PT Distributor Sumatera Barat 03', 'PT Distributor Gorontalo 01',
       'PT Distributor Banten 03', 'PT Distributor Sulawesi Tengah 01',
       'PT Distributor Aceh 03', 'PT Distributor Sulawesi Selatan 02',
       'PT Distributor Nusa Tenggara Timur 02',
       'PT Distributor Banten 02', 'PT Distributor Lampung 01',
       'PT Distributor Kalimantan Barat 01',
       'PT Distributor Jawa Tengah 01', 'PT Distributor Bali 03',
       'PT Distributor Bengkulu 01', 'PT Distributor Dki Jakarta 01',
       'PT Distributor Maluku Utara 01',
       'PT Distributor Sumatera Selatan 03',
       'PT Distributor Sulawesi Tenggara 02',
       'PT Distributor Jawa Timur 03',
       'PT Distributor Nusa Tenggara Barat 01', 'PT Distributor Aceh 02',
       'PT Distributor Sumatera Utara 02',
       'PT Distributor Sulawesi Selatan 03', 'PT Distributor Lampung 02',
       'PT Distributor Bali 01', 'PT Distributor Sumatera Selatan 02',
       'PT Distributor Sumatera Barat 01',
       'PT Distributor Dki Jakarta 02',
       'PT Distributor Kalimantan Tengah 03',
       'PT Distributor Kepulauan Riau 03',
       'PT Distributor Sumatera Utara 01', 'PT Distributor Jawa Barat 01',
       'PT Distributor Papua Barat 03',
       'PT Distributor Kalimantan Utara 03',
       'PT Distributor Sulawesi Utara 03',
       'PT Distributor Nusa Tenggara Timur 03'], dtype=object)

In [39]:
table_CA['nama_distributor'].unique()

array(['PT Distributor Aceh 03', 'PT Distributor Jambi 02',
       'PT Distributor Kepulauan Riau 03',
       'PT Distributor Kepulauan Riau 02', 'PT Distributor Riau 02',
       'PT Distributor Sumatera Barat 03',
       'PT Distributor Sumatera Barat 01',
       'PT Distributor Sumatera Utara 03', 'PT Distributor Jambi 01',
       'PT Distributor Lampung 02', 'PT Distributor Sumatera Selatan 01',
       'PT Distributor Banten 02', 'PT Distributor Banten 01',
       'PT Distributor Jawa Barat 02', 'PT Distributor Jawa Barat 01',
       'PT Distributor Jawa Tengah 03', 'PT Distributor Bali 02',
       'PT Distributor Bali 01', 'PT Distributor Jawa Timur 03',
       'PT Distributor Kalimantan Barat 03',
       'PT Distributor Kalimantan Tengah 01', 'PT Distributor Maluku 03',
       'PT Distributor Maluku 01',
       'PT Distributor Nusa Tenggara Barat 03', 'PT Distributor Papua 01',
       'PT Distributor Sulawesi Barat 02',
       'PT Distributor Sulawesi Selatan 01',
       'PT Distributor Sulawesi Tengah 03',
       'PT Distributor Sulawesi Tengah 02',
       'PT Distributor Sulawesi Tenggara 03',
       'PT Distributor Sulawesi Utara 02', 'PT Distributor Aceh 01',
       'PT Distributor Bengkulu 03', 'PT Distributor Kepulauan Riau 01',
       'PT Distributor Riau 03', 'PT Distributor Sumatera Selatan 02',
       'PT Distributor Sumatera Selatan 03',
       'PT Distributor Jawa Tengah 02', 'PT Distributor Jawa Tengah 01',
       'PT Distributor Kepulauan Bangka Belitung 02',
       'PT Distributor Kalimantan Barat 02',
       'PT Distributor Kalimantan Selatan 02',
       'PT Distributor Kalimantan Selatan 01',
       'PT Distributor Kalimantan Utara 02',
       'PT Distributor Nusa Tenggara Timur 01',
       'PT Distributor Nusa Tenggara Timur 02', 'PT Distributor Papua 02',
       'PT Distributor Papua Barat 02',
       'PT Distributor Sulawesi Selatan 02',
       'PT Distributor Sulawesi Tengah 01',
       'PT Distributor Sulawesi Tenggara 02',
       'PT Distributor Sulawesi Tenggara 01',
       'PT Distributor Sulawesi Utara 01', 'PT Distributor Aceh 02',
       'PT Distributor Riau 01', 'PT Distributor Sumatera Barat 02',
       'PT Distributor Lampung 01', 'PT Distributor Banten 03',
       'PT Distributor Di Yogyakarta 01', 'PT Distributor Dki Jakarta 01',
       'PT Distributor Jawa Barat 03',
       'PT Distributor Kalimantan Barat 01',
       'PT Distributor Gorontalo 01', 'PT Distributor Gorontalo 02',
       'PT Distributor Kalimantan Selatan 03',
       'PT Distributor Maluku Utara 02',
       'PT Distributor Nusa Tenggara Barat 02',
       'PT Distributor Nusa Tenggara Barat 01',
       'PT Distributor Sulawesi Barat 03', 'PT Distributor Bengkulu 01',
       'PT Distributor Bengkulu 02', 'PT Distributor Jambi 03',
       'PT Distributor Di Yogyakarta 02', 'PT Distributor Jawa Timur 01',
       'PT Distributor Kalimantan Tengah 02',
       'PT Distributor Kalimantan Timur 02',
       'PT Distributor Kalimantan Timur 03',
       'PT Distributor Nusa Tenggara Timur 03',
       'PT Distributor Sulawesi Barat 01',
       'PT Distributor Di Yogyakarta 03', 'PT Distributor Dki Jakarta 03',
       'PT Distributor Kepulauan Bangka Belitung 01',
       'PT Distributor Kepulauan Bangka Belitung 03',
       'PT Distributor Kalimantan Utara 01',
       'PT Distributor Papua Barat 01',
       'PT Distributor Sulawesi Utara 03',
       'PT Distributor Dki Jakarta 02', 'PT Distributor Gorontalo 03',
       'PT Distributor Kalimantan Timur 01',
       'PT Distributor Papua Barat 03',
       'PT Distributor Sulawesi Selatan 03', 'PT Distributor Bali 03',
       'PT Distributor Jawa Timur 02', 'PT Distributor Maluku 02',
       'PT Distributor Papua 03', 'PT Distributor Sumatera Utara 01',
       'PT Distributor Kalimantan Utara 03',
       'PT Distributor Maluku Utara 03', 'PT Distributor Maluku Utara 01',
       'PT Distributor Kalimantan Tengah 03',
       'PT Distributor Sumatera Utara 02', 'PT Distributor Lampung 03'],
      dtype=object)

### Export Hasil Pembersihan Awal Dataset

In [40]:
table_survey.to_csv('table_survey_new.csv', index=False)
table_CA.to_csv('table_CA_new.csv', index=False)
table_sell_in.to_csv('table_sell_in_new.csv', index=False)
table_sell_out.to_csv('table_sell_out_new.csv', index=False)